#!/usr/bin/env python3
"""Time the narration with Edge TTS and write src/timing.ts (scene lengths, word timing, captions) and SCRIPT.md.
The generated clips in public/audio/ are the narration the video plays.
Usage: python3 scripts/generate-voiceovers.py [--force]"""
import asyncio, json, os, re, sys
import edge_tts

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
AUDIO = os.path.join(ROOT, "public/audio")
cfg = json.load(open(os.path.join(HERE, "vo.json")))
FORCE = "--force" in sys.argv
RATE = cfg.get("rate", "+0%")
alnum = lambda s: len(re.sub(r"[^a-z0-9]", "", s.lower()))

async def synth(text, name):
    mp3, meta = os.path.join(AUDIO, name + ".mp3"), os.path.join(AUDIO, name + ".json")
    if not FORCE and os.path.exists(mp3) and os.path.exists(meta):
        cached = json.load(open(meta))
        if cached["text"] == text and cached["voice"] == cfg["voice"] and cached.get("rate") == RATE: return cached["words"]
    words = []
    com = edge_tts.Communicate(text, cfg["voice"], rate=RATE, boundary="WordBoundary")
    with open(mp3, "wb") as fh:
        async for c in com.stream():
            if c["type"] == "audio": fh.write(c["data"])
            elif c["type"] == "WordBoundary":
                s = c["offset"] / 1e7
                words.append({"t": c["text"], "s": s, "e": s + c["duration"] / 1e7})
    json.dump({"text": text, "voice": cfg["voice"], "rate": RATE, "words": words}, open(meta, "w"))
    print("generated", name, f"{words[-1]['e']:.2f}s")
    return words

async def main():
    os.makedirs(AUDIO, exist_ok=True)
    scenes, start = {}, 0.0
    for sc in cfg["scenes"]:
        t, clips, words, caps = 0.0, [], [], []
        for i, clip in enumerate(sc["clips"]):
            pairs = [(c, c) if isinstance(c, str) else tuple(c) for c in clip["captions"]]
            name = f"{sc['id']}-{i}"
            w = await synth(" ".join(p[0] for p in pairs), name)
            t += clip["gap"]
            clips.append({"file": f"audio/{name}.mp3", "start": round(t, 3)})
            k = 0
            for say, show in pairs:
                need, got, k0 = alnum(say), 0, k
                while k < len(w) and got < need:
                    got += alnum(w[k]["t"]); k += 1
                caps.append({"text": show, "s": round(t + w[k0]["s"], 3), "e": round(t + w[k - 1]["e"], 3)})
            words += [{"t": x["t"], "s": round(t + x["s"], 3), "e": round(t + x["e"], 3)} for x in w]
            t += w[-1]["e"]
        dur = round(t + sc.get("tail", 0.5), 2)
        scenes[sc["id"]] = {"start": round(start, 2), "duration": dur, "clips": clips, "captions": caps, "words": words}
        print(f"{sc['id']:8s} start={start:6.2f} dur={dur:5.2f}")
        start += dur - cfg["crossfade"]
    total = start + cfg["crossfade"]
    with open(os.path.join(ROOT, "src/timing.ts"), "w") as fh:
        fh.write("// Auto-generated by scripts/generate-voiceovers.py. Do not edit.\n")
        fh.write("export type Word = { t: string; s: number; e: number };\n")
        fh.write("export type SceneTiming = { start: number; duration: number; clips: { file: string; start: number }[]; captions: { text: string; s: number; e: number }[]; words: Word[] };\n")
        fh.write(f"export const CROSSFADE = {cfg['crossfade']};\n")
        fh.write(f"export const VO_TOTAL = {round(total, 2)};\n")
        fh.write("export const TIMING: Record<string, SceneTiming> = " + json.dumps(scenes, indent=1) + ";\n")
    # SCRIPT.md: every line with the time it is on screen, for recording the real voiceover
    VISUALS = {
        "hook": "A normal map app: Noyes to Goldwin Smith, 9 min. Cut to the Libe Slope stairs; a red box lands on them.",
        "problem": "The same map. Barrier markers appear on the route and the 9 min is struck out.",
        "turn": "TANDEM wordmark and tagline, then a phone slides in and a message is typed.",
        "request": "The iMessage thread: the request is sent, Tandem gives a thumbs-up and replies.",
        "scout": "The live dashboard: photos checked one by one (clear, clear, clear), then everything stops on the stairs. Route B gets its warnings.",
        "reply": "The whole text conversation on the phone, with each message enlarged on the right: map, flagged photo and date, Google vs Tandem, entrance check, weather and bus, the walk preview.",
        "memory": "You report a problem by text; a new pin drops on the campus barrier map.",
        "night": "Night mode: the routes coloured by street lighting, then the view pulls back to the blue-light phones.",
        "more": "Six tiles, one per feature, landing as each is named.",
        "closing": "The map app again; Tandem's route replaces Google's. Then TANDEM and the tagline alone.",
        "live": "Title card: LIVE DEMO. Fades to black for the recorded demo.",
    }
    clock = lambda sec: f"{int(sec // 60)}:{sec % 60:04.1f}"
    with open(os.path.join(ROOT, "SCRIPT.md"), "w") as fh:
        fh.write("# Tandem demo video: voiceover script\n\n")
        fh.write(f"The video plays an AI voiceover with captions. To replace it with a recorded one, read to these times ({clock(total)} in total). ")
        fh.write("Each line's caption is on screen from its start to its end time, and the visuals are cued to the same moments, so starting each line on its start time keeps everything in sync.\n\n")
        fh.write("Auto-generated by `scripts/generate-voiceovers.py` from `scripts/vo.json`. Edit the wording there and run `npm run voiceover`.\n")
        for sc in cfg["scenes"]:
            tm = scenes[sc["id"]]
            fh.write(f"\n## {sc['id'].capitalize()} ({clock(tm['start'])} to {clock(tm['start'] + tm['duration'])})\n\n")
            fh.write(f"On screen: {VISUALS.get(sc['id'], '')}\n\n| Start | End | Line |\n|---|---|---|\n")
            for cap in tm["captions"]:
                fh.write(f"| {clock(tm['start'] + cap['s'])} | {clock(tm['start'] + cap['e'])} | {cap['text']} |\n")
    print(f"total {total:.1f}s")

asyncio.run(main())
