#!/usr/bin/env python3
"""Generate Edge TTS voiceover clips from vo.json and write src/timing.ts (clip offsets, word timing, captions, scene starts).
Usage: python3 scripts/generate-voiceovers.py [--force]"""
import asyncio, json, os, re, sys
import edge_tts

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
AUDIO = os.path.join(ROOT, "public/audio")
cfg = json.load(open(os.path.join(HERE, "vo.json")))
FORCE = "--force" in sys.argv
alnum = lambda s: len(re.sub(r"[^a-z0-9]", "", s.lower()))

async def synth(text, name):
    mp3, meta = os.path.join(AUDIO, name + ".mp3"), os.path.join(AUDIO, name + ".json")
    if not FORCE and os.path.exists(mp3) and os.path.exists(meta):
        cached = json.load(open(meta))
        if cached["text"] == text and cached["voice"] == cfg["voice"]: return cached["words"]
    words = []
    com = edge_tts.Communicate(text, cfg["voice"], boundary="WordBoundary")
    with open(mp3, "wb") as fh:
        async for c in com.stream():
            if c["type"] == "audio": fh.write(c["data"])
            elif c["type"] == "WordBoundary":
                s = c["offset"] / 1e7
                words.append({"t": c["text"], "s": s, "e": s + c["duration"] / 1e7})
    json.dump({"text": text, "voice": cfg["voice"], "words": words}, open(meta, "w"))
    print("generated", name, f"{words[-1]['e']:.2f}s")
    return words

async def main():
    os.makedirs(AUDIO, exist_ok=True)
    scenes, start = {}, 0.0
    for sc in cfg["scenes"]:
        t, clips, words, caps = 0.0, [], [], []
        for i, clip in enumerate(sc["clips"]):
            pairs = [(c, c) if isinstance(c, str) else tuple(c) for c in clip["captions"]]
            name = f"{sc['id']}-{i}"
            w = await synth(" ".join(p[0] for p in pairs), name)
            t += clip["gap"]
            clips.append({"file": f"audio/{name}.mp3", "start": round(t, 3)})
            k = 0
            for say, show in pairs:
                need, got, k0 = alnum(say), 0, k
                while k < len(w) and got < need:
                    got += alnum(w[k]["t"]); k += 1
                caps.append({"text": show, "s": round(t + w[k0]["s"], 3), "e": round(t + w[k - 1]["e"], 3)})
            words += [{"t": x["t"], "s": round(t + x["s"], 3), "e": round(t + x["e"], 3)} for x in w]
            t += w[-1]["e"]
        dur = round(t + sc.get("tail", 0.5), 2)
        scenes[sc["id"]] = {"start": round(start, 2), "duration": dur, "clips": clips, "captions": caps, "words": words}
        print(f"{sc['id']:8s} start={start:6.2f} dur={dur:5.2f}")
        start += dur - cfg["crossfade"]
    total = start + cfg["crossfade"]
    with open(os.path.join(ROOT, "src/timing.ts"), "w") as fh:
        fh.write("// Auto-generated by scripts/generate-voiceovers.py. Do not edit.\n")
        fh.write("export type Word = { t: string; s: number; e: number };\n")
        fh.write("export type SceneTiming = { start: number; duration: number; clips: { file: string; start: number }[]; captions: { text: string; s: number; e: number }[]; words: Word[] };\n")
        fh.write(f"export const CROSSFADE = {cfg['crossfade']};\n")
        fh.write(f"export const VO_TOTAL = {round(total, 2)};\n")
        fh.write("export const TIMING: Record<string, SceneTiming> = " + json.dumps(scenes, indent=1) + ";\n")
    print(f"total {total:.1f}s")

asyncio.run(main())
