#!/usr/bin/env python3
"""Copy the demo Street View frames, stitch an OSM basemap, and write src/data.ts from fixtures/demo-scout.json."""
import io, json, math, os, shutil, urllib.request
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
REPO = os.path.dirname(ROOT)
Z, TILES_W, TILES_H = 18, 10, 9

def decode(s):
    pts, i, lat, lng = [], 0, 0, 0
    while i < len(s):
        for k in (0, 1):
            shift = res = 0
            while True:
                b = ord(s[i]) - 63; i += 1
                res |= (b & 0x1F) << shift; shift += 5
                if b < 0x20: break
            d = ~(res >> 1) if res & 1 else res >> 1
            if k == 0: lat += d
            else: lng += d
        pts.append((lat / 1e5, lng / 1e5))
    return pts

def world(lat, lng):
    n = 256 * 2 ** Z
    x = (lng + 180) / 360 * n
    y = (1 - math.asinh(math.tan(math.radians(lat))) / math.pi) / 2 * n
    return x, y

scout = json.load(open(os.path.join(REPO, "fixtures/demo-scout.json")))
routes = {r["routeId"]: [world(*p) for p in decode(r["polyline"])] for r in scout["routes"]}
allp = [p for r in routes.values() for p in r]
cx = (min(p[0] for p in allp) + max(p[0] for p in allp)) / 2
cy = (min(p[1] for p in allp) + max(p[1] for p in allp)) / 2
tx0 = round(cx / 256 - TILES_W / 2); ty0 = round(cy / 256 - TILES_H / 2) - 1  # extra room to the north for the blue-light phones
ox, oy = tx0 * 256, ty0 * 256

cache = os.path.join(HERE, ".tiles"); os.makedirs(cache, exist_ok=True)
canvas = Image.new("RGB", (TILES_W * 256, TILES_H * 256))
for i in range(TILES_W):
    for j in range(TILES_H):
        f = os.path.join(cache, f"{Z}-{tx0+i}-{ty0+j}.png")
        if not os.path.exists(f):
            req = urllib.request.Request(f"https://tile.openstreetmap.org/{Z}/{tx0+i}/{ty0+j}.png",
                                         headers={"User-Agent": "tandem-demo-video/1.0 (hackathon project)"})
            open(f, "wb").write(urllib.request.urlopen(req).read())
        canvas.paste(Image.open(f).convert("RGB"), (i * 256, j * 256))
canvas.save(os.path.join(ROOT, "public/map.png"))

# The dashboard's .dark-tiles CSS filter, baked in: invert(1) hue-rotate(195deg) brightness(0.82) contrast(0.92) saturate(0.45)
import numpy as np
c, sn = math.cos(math.radians(195)), math.sin(math.radians(195))
HUE = np.array([[0.213 + c * 0.787 - sn * 0.213, 0.715 - c * 0.715 - sn * 0.715, 0.072 - c * 0.072 + sn * 0.928],
                [0.213 - c * 0.213 + sn * 0.143, 0.715 + c * 0.285 + sn * 0.140, 0.072 - c * 0.072 - sn * 0.283],
                [0.213 - c * 0.213 - sn * 0.787, 0.715 - c * 0.715 + sn * 0.715, 0.072 + c * 0.928 + sn * 0.072]])
sat = 0.45
SAT = np.array([[0.213 + 0.787 * sat, 0.715 - 0.715 * sat, 0.072 - 0.072 * sat],
                [0.213 - 0.213 * sat, 0.715 + 0.285 * sat, 0.072 - 0.072 * sat],
                [0.213 - 0.213 * sat, 0.715 - 0.715 * sat, 0.072 + 0.928 * sat]])
px_ = 1 - np.asarray(canvas, dtype=np.float32) / 255
px_ = np.clip(px_ @ HUE.T, 0, 1) * 0.82
px_ = np.clip((px_ - 0.5) * 0.92 + 0.5, 0, 1)
px_ = np.clip(px_ @ SAT.T, 0, 1)
Image.fromarray((px_ * 255).astype(np.uint8)).save(os.path.join(ROOT, "public/map-dark.jpg"), quality=90)

frames = os.path.join(REPO, "fixtures/demo-frames")
for f in os.listdir(frames):
    if f.endswith(".jpg"): shutil.copy(os.path.join(frames, f), os.path.join(ROOT, "public/frames", f))

r1 = lambda v: round(v, 1)
out = {
    "MAP": {"w": TILES_W * 256, "h": TILES_H * 256},
    "FROM": scout["from"].split(",")[0], "TO": scout["to"].split(",")[0],
    "ROUTES": {
        r["routeId"]: {
            "durationMin": r["durationMin"], "score": r["score"],
            "points": [[r1(x - ox), r1(y - oy)] for x, y in routes[r["routeId"]]],
            "flags": [{
                "id": f["id"], "type": f["type"], "note": f["note"], "source": f["source"],
                "photoDate": f.get("photoDate"), "box": f.get("box"),
                "image": "frames/" + os.path.basename(f["imagePath"]),
                "x": r1(world(f["location"]["lat"], f["location"]["lng"])[0] - ox),
                "y": r1(world(f["location"]["lat"], f["location"]["lng"])[1] - oy),
            } for f in r["flags"]],
        } for r in scout["routes"]
    },
}
with open(os.path.join(ROOT, "src/data.ts"), "w") as fh:
    fh.write("// Auto-generated by scripts/prepare-assets.py from fixtures/demo-scout.json. Do not edit.\n")
    for k, v in out.items():
        fh.write(f"export const {k} = {json.dumps(v, indent=2)} as const;\n")
# ---- extras from OpenStreetMap (scripts/osm/area.json, fetched once from api.openstreetmap.org) ----
# Mirrors scout/night.ts (lighting along a route) and scout/entrance.ts (the destination's doors).
osm = json.load(open(os.path.join(HERE, "osm/area.json")))["elements"]
nodes = {e["id"]: e for e in osm if e["type"] == "node"}
ways = [e for e in osm if e["type"] == "way" and all(n in nodes for n in e["nodes"])]
LL = lambda w: [(nodes[n]["lat"], nodes[n]["lon"]) for n in w["nodes"]]
px = lambda lat, lng: [r1(world(lat, lng)[0] - ox), r1(world(lat, lng)[1] - oy)]

def meters(p, q):
    kx = 111320 * math.cos(math.radians(p[0]))
    return math.hypot((q[1] - p[1]) * kx, (q[0] - p[0]) * 110540)

def dist_to_way(p, pts):
    kx = 111320 * math.cos(math.radians(p[0]))
    xy = [((q[1] - p[1]) * kx, (q[0] - p[0]) * 110540) for q in pts]
    best = math.hypot(*xy[0])
    for (ax, ay), (bx, by) in zip(xy, xy[1:]):
        dx, dy = bx - ax, by - ay
        L = dx * dx + dy * dy
        t = max(0, min(1, -(ax * dx + ay * dy) / L)) if L else 0
        best = min(best, math.hypot(ax + t * dx, ay + t * dy))
    return best

def sample(pts, step):
    out, carry = [pts[0]], 0.0
    for a, b in zip(pts, pts[1:]):
        d = meters(a, b); t = step - carry
        while t <= d:
            out.append((a[0] + (b[0] - a[0]) * t / d, a[1] + (b[1] - a[1]) * t / d)); t += step
        carry = (carry + d) % step
    return out

LIT_YES = {"yes", "24/7", "automatic", "sunset-sunrise", "dusk-dawn", "interval", "limited"}
def light_of(tags):
    lit = tags.get("lit", "").lower()
    if not lit: return "unknown"
    if lit == "no": return "unlit"
    return "lit" if lit in LIT_YES or lit[0].isdigit() or ":" in lit else "unknown"

highways = [(w["tags"], LL(w)) for w in ways if "highway" in w.get("tags", {})]
def lighting(route_ll):
    pts = sample(route_ll, 10)
    lights = []
    for p in pts:
        on, on_d = None, 12
        for tags, wpts in highways:
            d = dist_to_way(p, wpts)
            if d <= on_d: on, on_d = tags, d
        lights.append(light_of(on) if on else "unknown")
    lights = ["lit" if l == "unknown" and 0 < i < len(lights) - 1 and lights[i - 1] == "lit" and lights[i + 1] == "lit" else l for i, l in enumerate(lights)]
    segs = []
    for p, l in zip(pts, lights):
        if segs and segs[-1]["light"] == l: segs[-1]["points"].append(px(*p))
        else:
            if segs: segs[-1]["points"].append(px(*p))
            segs.append({"light": l, "points": [px(*p)]})
    return {"litPct": round(100 * lights.count("lit") / len(lights)), "unlitPct": round(100 * lights.count("unlit") / len(lights)), "segments": segs}

night = {r["routeId"]: lighting(decode(r["polyline"])) for r in scout["routes"]}
# emergency phones across central campus (scripts/osm/phones.json, extracted from a wider OSM download)
phones = [px(n["lat"], n["lon"]) for n in json.load(open(os.path.join(HERE, "osm/phones.json")))]
phones_on_route = sum(1 for n in json.load(open(os.path.join(HERE, "osm/phones.json"))) if min(meters((n["lat"], n["lon"]), q) for r in scout["routes"] for q in sample(decode(r["polyline"]), 10)) <= 40)

end = decode(scout["routes"][0]["polyline"])[-1]
bld = next(w for w in ways if w.get("tags", {}).get("name") == out["TO"] and "building" in w["tags"])
doors = [nodes[n] for n in bld["nodes"] if "entrance" in nodes[n].get("tags", {})]
tagged = [d for d in doors if d["tags"].get("wheelchair") or d["tags"].get("ramp") or d["tags"].get("automatic_door")]
assert not tagged and "wheelchair" not in bld["tags"], "entrance data changed: update the note logic to match scout/entrance.ts writeNote()"
entrance = {
    "note": "OpenStreetMap doesn't say which entrance is accessible, so it's worth calling ahead.",  # writeNote() for untagged doors
    "building": [px(*p) for p in LL(bld)],
    "doors": [{"x": px(d["lat"], d["lon"])[0], "y": px(d["lat"], d["lon"])[1], "kind": "other"} for d in doors],
    "legend": [{"kind": "other", "label": f"{len(doors)} mapped entrances, none tagged for wheelchair access"}],
}
with open(os.path.join(ROOT, "src/extras.ts"), "w") as fh:
    fh.write("// Auto-generated by scripts/prepare-assets.py from OpenStreetMap data. Do not edit.\n")
    fh.write("type Pt = [number, number];\n")
    fh.write("export const ENTRANCE: { note: string; building: Pt[]; doors: { x: number; y: number; kind: string }[]; legend: { kind: string; label: string }[] } | null = " + json.dumps(entrance) + ";\n")
    fh.write("export const NIGHT: Record<string, { litPct: number; unlitPct: number; segments: { light: string; points: Pt[] }[] }> = " + json.dumps(night) + ";\n")
    fh.write("export const PHONES: Pt[] = " + json.dumps(phones) + ";\n")
    fh.write(f"export const PHONES_ON_ROUTE = {phones_on_route}; // within 40 m, the app's rule\n")
    fh.write("// messaging/context.ts TANDEM_WEATHER=icy demo values\n")
    fh.write('export const WEATHER_DEMO = { tempF: 29, summary: "Freezing rain" };\n')
print("night", {k: (v["litPct"], v["unlitPct"], len(v["segments"])) for k, v in night.items()}, "phones", len(phones), "doors", len(doors))
print("map", canvas.size, {k: len(v) for k, v in routes.items()})
