#!/usr/bin/env python3
"""Copy the demo Street View frames, stitch an OSM basemap, and write src/data.ts from fixtures/demo-scout.json."""
import io, json, math, os, shutil, urllib.request
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
REPO = os.path.dirname(ROOT)
Z, TILES_W, TILES_H = 18, 10, 7

def decode(s):
    pts, i, lat, lng = [], 0, 0, 0
    while i < len(s):
        for k in (0, 1):
            shift = res = 0
            while True:
                b = ord(s[i]) - 63; i += 1
                res |= (b & 0x1F) << shift; shift += 5
                if b < 0x20: break
            d = ~(res >> 1) if res & 1 else res >> 1
            if k == 0: lat += d
            else: lng += d
        pts.append((lat / 1e5, lng / 1e5))
    return pts

def world(lat, lng):
    n = 256 * 2 ** Z
    x = (lng + 180) / 360 * n
    y = (1 - math.asinh(math.tan(math.radians(lat))) / math.pi) / 2 * n
    return x, y

scout = json.load(open(os.path.join(REPO, "fixtures/demo-scout.json")))
routes = {r["routeId"]: [world(*p) for p in decode(r["polyline"])] for r in scout["routes"]}
allp = [p for r in routes.values() for p in r]
cx = (min(p[0] for p in allp) + max(p[0] for p in allp)) / 2
cy = (min(p[1] for p in allp) + max(p[1] for p in allp)) / 2
tx0 = round(cx / 256 - TILES_W / 2); ty0 = round(cy / 256 - TILES_H / 2)
ox, oy = tx0 * 256, ty0 * 256

cache = os.path.join(HERE, ".tiles"); os.makedirs(cache, exist_ok=True)
canvas = Image.new("RGB", (TILES_W * 256, TILES_H * 256))
for i in range(TILES_W):
    for j in range(TILES_H):
        f = os.path.join(cache, f"{Z}-{tx0+i}-{ty0+j}.png")
        if not os.path.exists(f):
            req = urllib.request.Request(f"https://tile.openstreetmap.org/{Z}/{tx0+i}/{ty0+j}.png",
                                         headers={"User-Agent": "tandem-demo-video/1.0 (hackathon project)"})
            open(f, "wb").write(urllib.request.urlopen(req).read())
        canvas.paste(Image.open(f).convert("RGB"), (i * 256, j * 256))
canvas.save(os.path.join(ROOT, "public/map.png"))

frames = os.path.join(REPO, "fixtures/demo-frames")
for f in os.listdir(frames):
    if f.endswith(".jpg"): shutil.copy(os.path.join(frames, f), os.path.join(ROOT, "public/frames", f))

r1 = lambda v: round(v, 1)
out = {
    "MAP": {"w": TILES_W * 256, "h": TILES_H * 256},
    "FROM": scout["from"].split(",")[0], "TO": scout["to"].split(",")[0],
    "ROUTES": {
        r["routeId"]: {
            "durationMin": r["durationMin"], "score": r["score"],
            "points": [[r1(x - ox), r1(y - oy)] for x, y in routes[r["routeId"]]],
            "flags": [{
                "id": f["id"], "type": f["type"], "note": f["note"], "source": f["source"],
                "photoDate": f.get("photoDate"), "box": f.get("box"),
                "image": "frames/" + os.path.basename(f["imagePath"]),
                "x": r1(world(f["location"]["lat"], f["location"]["lng"])[0] - ox),
                "y": r1(world(f["location"]["lat"], f["location"]["lng"])[1] - oy),
            } for f in r["flags"]],
        } for r in scout["routes"]
    },
}
with open(os.path.join(ROOT, "src/data.ts"), "w") as fh:
    fh.write("// Auto-generated by scripts/prepare-assets.py from fixtures/demo-scout.json. Do not edit.\n")
    for k, v in out.items():
        fh.write(f"export const {k} = {json.dumps(v, indent=2)} as const;\n")
print("map", canvas.size, {k: len(v) for k, v in routes.items()})
