// Auto-generated by scripts/prepare-assets.py from fixtures/demo-scout.json. Do not edit.
export const MAP = {
  "w": 2560,
  "h": 1792
} as const;
export const FROM = "Noyes Community Recreation Center" as const;
export const TO = "Goldwin Smith Hall" as const;
export const ROUTES = {
  "A": {
    "durationMin": 9.4,
    "score": 9,
    "points": [
      [
        810.8,
        1314.9
      ],
      [
        859.3,
        1322.5
      ],
      [
        853.7,
        1294.7
      ],
      [
        876.1,
        1277.0
      ],
      [
        870.5,
        1029.4
      ],
      [
        928.3,
        1021.8
      ],
      [
        997.2,
        999.1
      ],
      [
        1109.1,
        938.5
      ],
      [
        1181.8,
        928.4
      ],
      [
        1252.6,
        933.4
      ],
      [
        1334.6,
        928.4
      ],
      [
        1344.0,
        920.8
      ],
      [
        1371.9,
        930.9
      ],
      [
        1383.1,
        933.4
      ],
      [
        1426.0,
        865.2
      ],
      [
        1440.9,
        857.6
      ],
      [
        1549.0,
        749.0
      ],
      [
        1591.9,
        711.1
      ],
      [
        1591.9,
        698.5
      ]
    ],
    "flags": [
      {
        "id": "a1",
        "type": "steps",
        "note": "14 steps on the Libe Slope path, no ramp",
        "source": "osm",
        "photoDate": "2009-07",
        "box": {
          "x": 0.3,
          "y": 0.56,
          "w": 0.4,
          "h": 0.36
        },
        "image": "frames/xQmQysnZDx8sOIMLjPdHoQ.jpg",
        "x": 1226.8,
        "y": 932.3
      }
    ]
  },
  "B": {
    "durationMin": 9.5,
    "score": 5,
    "points": [
      [
        810.8,
        1314.9
      ],
      [
        859.3,
        1322.5
      ],
      [
        853.7,
        1294.7
      ],
      [
        876.1,
        1277.0
      ],
      [
        870.5,
        1029.4
      ],
      [
        891.0,
        1024.4
      ],
      [
        973.0,
        963.7
      ],
      [
        1004.7,
        935.9
      ],
      [
        1211.6,
        794.5
      ],
      [
        1224.7,
        766.7
      ],
      [
        1239.6,
        756.6
      ],
      [
        1256.3,
        754.0
      ],
      [
        1273.1,
        738.9
      ],
      [
        1293.6,
        736.4
      ],
      [
        1336.5,
        741.4
      ],
      [
        1368.2,
        708.6
      ],
      [
        1517.3,
        701.0
      ],
      [
        1549.0,
        749.0
      ],
      [
        1591.9,
        711.1
      ],
      [
        1591.9,
        698.5
      ]
    ],
    "flags": [
      {
        "id": "b1",
        "type": "steep_grade",
        "note": "Steep climb up Libe Slope.",
        "source": "elevation",
        "photoDate": "2009-07",
        "box": null,
        "image": "frames/PWx35RSMyO_sE6Oyp2ti6g.jpg",
        "x": 951.5,
        "y": 979.4
      },
      {
        "id": "b2",
        "type": "broken_sidewalk",
        "note": "Cracked, uneven path partway up Libe Slope.",
        "source": "vision",
        "photoDate": "2009-07",
        "box": {
          "x": 0.24,
          "y": 0.57,
          "w": 0.24,
          "h": 0.1
        },
        "image": "frames/6nwbFUCBXIrFnEt9fx5yIg.jpg",
        "x": 1034.0,
        "y": 915.4
      }
    ]
  }
} as const;
