// Auto-generated by scripts/prepare-assets.py from fixtures/demo-scout.json. Do not edit.
export const MAP = {
  "w": 2560,
  "h": 2304
} as const;
export const FROM = "Noyes Community Recreation Center" as const;
export const TO = "Goldwin Smith Hall" as const;
export const ROUTES = {
  "A": {
    "durationMin": 9.4,
    "score": 9,
    "points": [
      [
        810.8,
        1826.9
      ],
      [
        859.3,
        1834.5
      ],
      [
        853.7,
        1806.7
      ],
      [
        876.1,
        1789.0
      ],
      [
        870.5,
        1541.4
      ],
      [
        928.3,
        1533.8
      ],
      [
        997.2,
        1511.1
      ],
      [
        1109.1,
        1450.5
      ],
      [
        1181.8,
        1440.4
      ],
      [
        1252.6,
        1445.4
      ],
      [
        1334.6,
        1440.4
      ],
      [
        1344.0,
        1432.8
      ],
      [
        1371.9,
        1442.9
      ],
      [
        1383.1,
        1445.4
      ],
      [
        1426.0,
        1377.2
      ],
      [
        1440.9,
        1369.6
      ],
      [
        1549.0,
        1261.0
      ],
      [
        1591.9,
        1223.1
      ],
      [
        1591.9,
        1210.5
      ]
    ],
    "flags": [
      {
        "id": "a1",
        "type": "steps",
        "note": "14 steps on the Libe Slope path, no ramp",
        "source": "osm",
        "photoDate": "2009-07",
        "box": {
          "x": 0.3,
          "y": 0.56,
          "w": 0.4,
          "h": 0.36
        },
        "image": "frames/xQmQysnZDx8sOIMLjPdHoQ.jpg",
        "x": 1226.8,
        "y": 1444.3
      }
    ]
  },
  "B": {
    "durationMin": 9.5,
    "score": 5,
    "points": [
      [
        810.8,
        1826.9
      ],
      [
        859.3,
        1834.5
      ],
      [
        853.7,
        1806.7
      ],
      [
        876.1,
        1789.0
      ],
      [
        870.5,
        1541.4
      ],
      [
        891.0,
        1536.4
      ],
      [
        973.0,
        1475.7
      ],
      [
        1004.7,
        1447.9
      ],
      [
        1211.6,
        1306.5
      ],
      [
        1224.7,
        1278.7
      ],
      [
        1239.6,
        1268.6
      ],
      [
        1256.3,
        1266.0
      ],
      [
        1273.1,
        1250.9
      ],
      [
        1293.6,
        1248.4
      ],
      [
        1336.5,
        1253.4
      ],
      [
        1368.2,
        1220.6
      ],
      [
        1517.3,
        1213.0
      ],
      [
        1549.0,
        1261.0
      ],
      [
        1591.9,
        1223.1
      ],
      [
        1591.9,
        1210.5
      ]
    ],
    "flags": [
      {
        "id": "b1",
        "type": "steep_grade",
        "note": "Steep climb up Libe Slope.",
        "source": "elevation",
        "photoDate": "2009-07",
        "box": null,
        "image": "frames/PWx35RSMyO_sE6Oyp2ti6g.jpg",
        "x": 951.5,
        "y": 1491.4
      },
      {
        "id": "b2",
        "type": "broken_sidewalk",
        "note": "Cracked, uneven path partway up Libe Slope.",
        "source": "vision",
        "photoDate": "2009-07",
        "box": {
          "x": 0.24,
          "y": 0.57,
          "w": 0.24,
          "h": 0.1
        },
        "image": "frames/6nwbFUCBXIrFnEt9fx5yIg.jpg",
        "x": 1034.0,
        "y": 1427.4
      }
    ]
  }
} as const;
