// Auto-generated by scripts/generate-voiceovers.py. Do not edit.
export type Word = { t: string; s: number; e: number };
export type SceneTiming = { start: number; duration: number; clips: { file: string; start: number }[]; captions: { text: string; s: number; e: number }[]; words: Word[] };
export const CROSSFADE = 0.5;
export const VO_TOTAL = 81.24;
export const TIMING: Record<string, SceneTiming> = {
 "hook": {
  "start": 0.0,
  "duration": 7.04,
  "clips": [
   {
    "file": "audio/hook-0.mp3",
    "start": 1.6
   },
   {
    "file": "audio/hook-1.mp3",
    "start": 3.775
   }
  ],
  "captions": [
   {
    "text": "Your map says nine minutes.",
    "s": 1.7,
    "e": 3.075
   },
   {
    "text": "It doesn't say there are fourteen steps in the way.",
    "s": 3.875,
    "e": 6.138
   }
  ],
  "words": [
   {
    "t": "Your",
    "s": 1.7,
    "e": 1.788
   },
   {
    "t": "map",
    "s": 1.8,
    "e": 2.062
   },
   {
    "t": "says",
    "s": 2.075,
    "e": 2.3
   },
   {
    "t": "nine",
    "s": 2.312,
    "e": 2.588
   },
   {
    "t": "minutes",
    "s": 2.6,
    "e": 3.075
   },
   {
    "t": "It",
    "s": 3.875,
    "e": 3.963
   },
   {
    "t": "doesn't",
    "s": 3.975,
    "e": 4.25
   },
   {
    "t": "say",
    "s": 4.263,
    "e": 4.5
   },
   {
    "t": "there",
    "s": 4.513,
    "e": 4.638
   },
   {
    "t": "are",
    "s": 4.65,
    "e": 4.738
   },
   {
    "t": "fourteen",
    "s": 4.75,
    "e": 5.263
   },
   {
    "t": "steps",
    "s": 5.275,
    "e": 5.65
   },
   {
    "t": "in",
    "s": 5.663,
    "e": 5.725
   },
   {
    "t": "the",
    "s": 5.738,
    "e": 5.825
   },
   {
    "t": "way",
    "s": 5.838,
    "e": 6.138
   }
  ]
 },
 "problem": {
  "start": 6.54,
  "duration": 9.04,
  "clips": [
   {
    "file": "audio/problem-0.mp3",
    "start": 0.6
   },
   {
    "file": "audio/problem-1.mp3",
    "start": 6.0
   }
  ],
  "captions": [
   {
    "text": "A route can look completely valid on a map",
    "s": 0.688,
    "e": 2.975
   },
   {
    "text": "and still be unusable for the person taking it.",
    "s": 3.3,
    "e": 5.6
   },
   {
    "text": "You usually find that out when you're already there.",
    "s": 6.1,
    "e": 8.137
   }
  ],
  "words": [
   {
    "t": "A",
    "s": 0.688,
    "e": 0.725
   },
   {
    "t": "route",
    "s": 0.738,
    "e": 1.038
   },
   {
    "t": "can",
    "s": 1.05,
    "e": 1.2
   },
   {
    "t": "look",
    "s": 1.212,
    "e": 1.363
   },
   {
    "t": "completely",
    "s": 1.375,
    "e": 2.0
   },
   {
    "t": "valid",
    "s": 2.013,
    "e": 2.388
   },
   {
    "t": "on",
    "s": 2.4,
    "e": 2.5
   },
   {
    "t": "a",
    "s": 2.513,
    "e": 2.55
   },
   {
    "t": "map",
    "s": 2.562,
    "e": 2.975
   },
   {
    "t": "and",
    "s": 3.3,
    "e": 3.388
   },
   {
    "t": "still",
    "s": 3.4,
    "e": 3.637
   },
   {
    "t": "be",
    "s": 3.65,
    "e": 3.812
   },
   {
    "t": "unusable",
    "s": 3.825,
    "e": 4.462
   },
   {
    "t": "for",
    "s": 4.475,
    "e": 4.575
   },
   {
    "t": "the",
    "s": 4.587,
    "e": 4.662
   },
   {
    "t": "person",
    "s": 4.675,
    "e": 5.037
   },
   {
    "t": "taking",
    "s": 5.05,
    "e": 5.425
   },
   {
    "t": "it",
    "s": 5.438,
    "e": 5.6
   },
   {
    "t": "You",
    "s": 6.1,
    "e": 6.188
   },
   {
    "t": "usually",
    "s": 6.2,
    "e": 6.562
   },
   {
    "t": "find",
    "s": 6.575,
    "e": 6.875
   },
   {
    "t": "that",
    "s": 6.888,
    "e": 7.0
   },
   {
    "t": "out",
    "s": 7.013,
    "e": 7.188
   },
   {
    "t": "when",
    "s": 7.2,
    "e": 7.3
   },
   {
    "t": "you're",
    "s": 7.312,
    "e": 7.463
   },
   {
    "t": "already",
    "s": 7.475,
    "e": 7.825
   },
   {
    "t": "there",
    "s": 7.838,
    "e": 8.137
   }
  ]
 },
 "turn": {
  "start": 15.08,
  "duration": 6.28,
  "clips": [
   {
    "file": "audio/turn-0.mp3",
    "start": 1.1
   },
   {
    "file": "audio/turn-1.mp3",
    "start": 3.088
   },
   {
    "file": "audio/turn-2.mp3",
    "start": 4.125
   }
  ],
  "captions": [
   {
    "text": "Tandem walks the route first.",
    "s": 1.2,
    "e": 2.638
   },
   {
    "text": "No new app.",
    "s": 3.188,
    "e": 3.825
   },
   {
    "text": "You just text where you're going.",
    "s": 4.225,
    "e": 5.375
   }
  ],
  "words": [
   {
    "t": "Tandem",
    "s": 1.2,
    "e": 1.5
   },
   {
    "t": "walks",
    "s": 1.513,
    "e": 1.788
   },
   {
    "t": "the",
    "s": 1.8,
    "e": 1.875
   },
   {
    "t": "route",
    "s": 1.888,
    "e": 2.112
   },
   {
    "t": "first",
    "s": 2.125,
    "e": 2.638
   },
   {
    "t": "No",
    "s": 3.188,
    "e": 3.3
   },
   {
    "t": "new",
    "s": 3.313,
    "e": 3.538
   },
   {
    "t": "app.",
    "s": 3.55,
    "e": 3.825
   },
   {
    "t": "You",
    "s": 4.225,
    "e": 4.287
   },
   {
    "t": "just",
    "s": 4.3,
    "e": 4.5
   },
   {
    "t": "text",
    "s": 4.513,
    "e": 4.8
   },
   {
    "t": "where",
    "s": 4.812,
    "e": 4.9
   },
   {
    "t": "you're",
    "s": 4.912,
    "e": 5.025
   },
   {
    "t": "going",
    "s": 5.037,
    "e": 5.375
   }
  ]
 },
 "request": {
  "start": 20.86,
  "duration": 6.05,
  "clips": [
   {
    "file": "audio/request-0.mp3",
    "start": 0.6
   }
  ],
  "captions": [
   {
    "text": "You tell it where you're headed,",
    "s": 0.713,
    "e": 1.712
   },
   {
    "text": "the same way you'd text a friend.",
    "s": 2.025,
    "e": 3.65
   }
  ],
  "words": [
   {
    "t": "You",
    "s": 0.713,
    "e": 0.8
   },
   {
    "t": "tell",
    "s": 0.812,
    "e": 1.012
   },
   {
    "t": "it",
    "s": 1.025,
    "e": 1.1
   },
   {
    "t": "where",
    "s": 1.112,
    "e": 1.237
   },
   {
    "t": "you're",
    "s": 1.25,
    "e": 1.375
   },
   {
    "t": "headed",
    "s": 1.387,
    "e": 1.712
   },
   {
    "t": "the",
    "s": 2.025,
    "e": 2.112
   },
   {
    "t": "same",
    "s": 2.125,
    "e": 2.462
   },
   {
    "t": "way",
    "s": 2.475,
    "e": 2.663
   },
   {
    "t": "you'd",
    "s": 2.675,
    "e": 2.85
   },
   {
    "t": "text",
    "s": 2.863,
    "e": 3.175
   },
   {
    "t": "a",
    "s": 3.188,
    "e": 3.212
   },
   {
    "t": "friend",
    "s": 3.225,
    "e": 3.65
   }
  ]
 },
 "scout": {
  "start": 26.41,
  "duration": 22.33,
  "clips": [
   {
    "file": "audio/scout-0.mp3",
    "start": 1.6
   },
   {
    "file": "audio/scout-1.mp3",
    "start": 7.95
   },
   {
    "file": "audio/scout-2.mp3",
    "start": 8.775
   },
   {
    "file": "audio/scout-3.mp3",
    "start": 9.6
   },
   {
    "file": "audio/scout-4.mp3",
    "start": 11.325
   },
   {
    "file": "audio/scout-5.mp3",
    "start": 13.138
   },
   {
    "file": "audio/scout-6.mp3",
    "start": 15.938
   }
  ],
  "captions": [
   {
    "text": "Tandem samples Street View along each candidate route,",
    "s": 1.7,
    "e": 4.775
   },
   {
    "text": "and checks what it sees for physical barriers.",
    "s": 5.088,
    "e": 7.35
   },
   {
    "text": "Clear.",
    "s": 8.05,
    "e": 8.375
   },
   {
    "text": "Clear.",
    "s": 8.875,
    "e": 9.2
   },
   {
    "text": "Clear.",
    "s": 9.7,
    "e": 10.025
   },
   {
    "text": "Then, fourteen steps.",
    "s": 11.425,
    "e": 12.788
   },
   {
    "text": "No ramp.",
    "s": 13.238,
    "e": 13.738
   },
   {
    "text": "It also checks signals like elevation,",
    "s": 16.038,
    "e": 18.013
   },
   {
    "text": "so it can show you the tradeoffs instead of hiding them.",
    "s": 18.363,
    "e": 20.725
   }
  ],
  "words": [
   {
    "t": "Tandem",
    "s": 1.7,
    "e": 2.0
   },
   {
    "t": "samples",
    "s": 2.013,
    "e": 2.475
   },
   {
    "t": "Street",
    "s": 2.487,
    "e": 2.875
   },
   {
    "t": "View",
    "s": 2.888,
    "e": 3.163
   },
   {
    "t": "along",
    "s": 3.237,
    "e": 3.638
   },
   {
    "t": "each",
    "s": 3.75,
    "e": 3.95
   },
   {
    "t": "candidate",
    "s": 3.962,
    "e": 4.463
   },
   {
    "t": "route",
    "s": 4.475,
    "e": 4.775
   },
   {
    "t": "and",
    "s": 5.088,
    "e": 5.162
   },
   {
    "t": "checks",
    "s": 5.175,
    "e": 5.438
   },
   {
    "t": "what",
    "s": 5.45,
    "e": 5.562
   },
   {
    "t": "it",
    "s": 5.575,
    "e": 5.662
   },
   {
    "t": "sees",
    "s": 5.675,
    "e": 6.113
   },
   {
    "t": "for",
    "s": 6.125,
    "e": 6.275
   },
   {
    "t": "physical",
    "s": 6.287,
    "e": 6.688
   },
   {
    "t": "barriers",
    "s": 6.7,
    "e": 7.35
   },
   {
    "t": "Clear",
    "s": 8.05,
    "e": 8.375
   },
   {
    "t": "Clear",
    "s": 8.875,
    "e": 9.2
   },
   {
    "t": "Clear",
    "s": 9.7,
    "e": 10.025
   },
   {
    "t": "Then",
    "s": 11.425,
    "e": 11.7
   },
   {
    "t": "fourteen",
    "s": 11.863,
    "e": 12.275
   },
   {
    "t": "steps",
    "s": 12.288,
    "e": 12.788
   },
   {
    "t": "No",
    "s": 13.238,
    "e": 13.388
   },
   {
    "t": "ramp",
    "s": 13.4,
    "e": 13.738
   },
   {
    "t": "It",
    "s": 16.038,
    "e": 16.113
   },
   {
    "t": "also",
    "s": 16.125,
    "e": 16.425
   },
   {
    "t": "checks",
    "s": 16.438,
    "e": 16.775
   },
   {
    "t": "signals",
    "s": 16.788,
    "e": 17.2
   },
   {
    "t": "like",
    "s": 17.213,
    "e": 17.375
   },
   {
    "t": "elevation",
    "s": 17.475,
    "e": 18.013
   },
   {
    "t": "so",
    "s": 18.363,
    "e": 18.525
   },
   {
    "t": "it",
    "s": 18.538,
    "e": 18.6
   },
   {
    "t": "can",
    "s": 18.613,
    "e": 18.713
   },
   {
    "t": "show",
    "s": 18.725,
    "e": 18.938
   },
   {
    "t": "you",
    "s": 18.95,
    "e": 19.038
   },
   {
    "t": "the",
    "s": 19.05,
    "e": 19.138
   },
   {
    "t": "tradeoffs",
    "s": 19.15,
    "e": 19.75
   },
   {
    "t": "instead",
    "s": 19.763,
    "e": 20.075
   },
   {
    "t": "of",
    "s": 20.088,
    "e": 20.163
   },
   {
    "t": "hiding",
    "s": 20.175,
    "e": 20.538
   },
   {
    "t": "them",
    "s": 20.55,
    "e": 20.725
   }
  ]
 },
 "proof": {
  "start": 48.24,
  "duration": 8.43,
  "clips": [
   {
    "file": "audio/proof-0.mp3",
    "start": 0.8
   },
   {
    "file": "audio/proof-1.mp3",
    "start": 2.387
   }
  ],
  "captions": [
   {
    "text": "And it shows its evidence.",
    "s": 0.9,
    "e": 2.037
   },
   {
    "text": "You get the photo it flagged, when that image was taken,",
    "s": 2.487,
    "e": 5.262
   },
   {
    "text": "and a preview of the route before you leave.",
    "s": 5.562,
    "e": 7.525
   }
  ],
  "words": [
   {
    "t": "And",
    "s": 0.9,
    "e": 0.975
   },
   {
    "t": "it",
    "s": 0.988,
    "e": 1.05
   },
   {
    "t": "shows",
    "s": 1.062,
    "e": 1.375
   },
   {
    "t": "its",
    "s": 1.388,
    "e": 1.513
   },
   {
    "t": "evidence",
    "s": 1.525,
    "e": 2.037
   },
   {
    "t": "You",
    "s": 2.487,
    "e": 2.562
   },
   {
    "t": "get",
    "s": 2.575,
    "e": 2.712
   },
   {
    "t": "the",
    "s": 2.725,
    "e": 2.812
   },
   {
    "t": "photo",
    "s": 2.825,
    "e": 3.237
   },
   {
    "t": "it",
    "s": 3.25,
    "e": 3.325
   },
   {
    "t": "flagged",
    "s": 3.337,
    "e": 3.85
   },
   {
    "t": "when",
    "s": 4.137,
    "e": 4.237
   },
   {
    "t": "that",
    "s": 4.25,
    "e": 4.412
   },
   {
    "t": "image",
    "s": 4.425,
    "e": 4.662
   },
   {
    "t": "was",
    "s": 4.675,
    "e": 4.825
   },
   {
    "t": "taken",
    "s": 4.838,
    "e": 5.262
   },
   {
    "t": "and",
    "s": 5.562,
    "e": 5.637
   },
   {
    "t": "a",
    "s": 5.65,
    "e": 5.7
   },
   {
    "t": "preview",
    "s": 5.713,
    "e": 6.175
   },
   {
    "t": "of",
    "s": 6.188,
    "e": 6.262
   },
   {
    "t": "the",
    "s": 6.275,
    "e": 6.338
   },
   {
    "t": "route",
    "s": 6.35,
    "e": 6.675
   },
   {
    "t": "before",
    "s": 6.688,
    "e": 7.037
   },
   {
    "t": "you",
    "s": 7.05,
    "e": 7.15
   },
   {
    "t": "leave",
    "s": 7.162,
    "e": 7.525
   }
  ]
 },
 "better": {
  "start": 56.17,
  "duration": 13.99,
  "clips": [
   {
    "file": "audio/better-0.mp3",
    "start": 0.6
   },
   {
    "file": "audio/better-1.mp3",
    "start": 6.325
   },
   {
    "file": "audio/better-2.mp3",
    "start": 8.837
   }
  ],
  "captions": [
   {
    "text": "Here, the direct route takes 9.4 minutes,",
    "s": 0.738,
    "e": 3.788
   },
   {
    "text": "and runs straight into the stairs.",
    "s": 4.062,
    "e": 5.825
   },
   {
    "text": "The alternative takes 9.5.",
    "s": 6.437,
    "e": 8.387
   },
   {
    "text": "It avoids the staircase,",
    "s": 8.937,
    "e": 10.237
   },
   {
    "text": "while still warning you about the steep climb ahead.",
    "s": 10.487,
    "e": 12.787
   }
  ],
  "words": [
   {
    "t": "Here",
    "s": 0.738,
    "e": 1.012
   },
   {
    "t": "the",
    "s": 1.3,
    "e": 1.4
   },
   {
    "t": "direct",
    "s": 1.413,
    "e": 1.775
   },
   {
    "t": "route",
    "s": 1.788,
    "e": 2.138
   },
   {
    "t": "takes",
    "s": 2.212,
    "e": 2.513
   },
   {
    "t": "nine",
    "s": 2.525,
    "e": 2.825
   },
   {
    "t": "point",
    "s": 2.837,
    "e": 3.087
   },
   {
    "t": "four",
    "s": 3.1,
    "e": 3.312
   },
   {
    "t": "minutes",
    "s": 3.325,
    "e": 3.788
   },
   {
    "t": "and",
    "s": 4.062,
    "e": 4.237
   },
   {
    "t": "runs",
    "s": 4.25,
    "e": 4.562
   },
   {
    "t": "straight",
    "s": 4.575,
    "e": 4.987
   },
   {
    "t": "into",
    "s": 5.0,
    "e": 5.162
   },
   {
    "t": "the",
    "s": 5.175,
    "e": 5.25
   },
   {
    "t": "stairs",
    "s": 5.262,
    "e": 5.825
   },
   {
    "t": "The",
    "s": 6.437,
    "e": 6.5
   },
   {
    "t": "alternative",
    "s": 6.512,
    "e": 7.075
   },
   {
    "t": "takes",
    "s": 7.087,
    "e": 7.4
   },
   {
    "t": "nine",
    "s": 7.412,
    "e": 7.7
   },
   {
    "t": "point",
    "s": 7.712,
    "e": 7.975
   },
   {
    "t": "five",
    "s": 7.987,
    "e": 8.387
   },
   {
    "t": "It",
    "s": 8.937,
    "e": 9.0
   },
   {
    "t": "avoids",
    "s": 9.012,
    "e": 9.425
   },
   {
    "t": "the",
    "s": 9.437,
    "e": 9.537
   },
   {
    "t": "staircase",
    "s": 9.55,
    "e": 10.237
   },
   {
    "t": "while",
    "s": 10.487,
    "e": 10.637
   },
   {
    "t": "still",
    "s": 10.65,
    "e": 10.962
   },
   {
    "t": "warning",
    "s": 10.975,
    "e": 11.312
   },
   {
    "t": "you",
    "s": 11.325,
    "e": 11.475
   },
   {
    "t": "about",
    "s": 11.487,
    "e": 11.7
   },
   {
    "t": "the",
    "s": 11.712,
    "e": 11.787
   },
   {
    "t": "steep",
    "s": 11.8,
    "e": 12.112
   },
   {
    "t": "climb",
    "s": 12.125,
    "e": 12.4
   },
   {
    "t": "ahead",
    "s": 12.412,
    "e": 12.787
   }
  ]
 },
 "closing": {
  "start": 69.66,
  "duration": 11.58,
  "clips": [
   {
    "file": "audio/closing-0.mp3",
    "start": 0.7
   },
   {
    "file": "audio/closing-1.mp3",
    "start": 3.9
   },
   {
    "file": "audio/closing-2.mp3",
    "start": 7.5
   },
   {
    "file": "audio/closing-3.mp3",
    "start": 8.225
   }
  ],
  "captions": [
   {
    "text": "Navigation shouldn't just know where a path goes.",
    "s": 0.8,
    "e": 3.45
   },
   {
    "text": "It should help you understand whether you can actually take it.",
    "s": 4.0,
    "e": 6.6
   },
   {
    "text": "Tandem.",
    "s": 7.6,
    "e": 7.925
   },
   {
    "text": "It walks the route before you do.",
    "s": 8.325,
    "e": 9.775
   }
  ],
  "words": [
   {
    "t": "Navigation",
    "s": 0.8,
    "e": 1.438
   },
   {
    "t": "shouldn't",
    "s": 1.45,
    "e": 1.825
   },
   {
    "t": "just",
    "s": 1.837,
    "e": 2.1
   },
   {
    "t": "know",
    "s": 2.112,
    "e": 2.388
   },
   {
    "t": "where",
    "s": 2.4,
    "e": 2.537
   },
   {
    "t": "a",
    "s": 2.55,
    "e": 2.6
   },
   {
    "t": "path",
    "s": 2.612,
    "e": 2.95
   },
   {
    "t": "goes",
    "s": 2.963,
    "e": 3.45
   },
   {
    "t": "It",
    "s": 4.0,
    "e": 4.075
   },
   {
    "t": "should",
    "s": 4.088,
    "e": 4.288
   },
   {
    "t": "help",
    "s": 4.3,
    "e": 4.513
   },
   {
    "t": "you",
    "s": 4.525,
    "e": 4.675
   },
   {
    "t": "understand",
    "s": 4.688,
    "e": 5.288
   },
   {
    "t": "whether",
    "s": 5.3,
    "e": 5.525
   },
   {
    "t": "you",
    "s": 5.538,
    "e": 5.638
   },
   {
    "t": "can",
    "s": 5.65,
    "e": 5.763
   },
   {
    "t": "actually",
    "s": 5.775,
    "e": 6.138
   },
   {
    "t": "take",
    "s": 6.15,
    "e": 6.425
   },
   {
    "t": "it",
    "s": 6.438,
    "e": 6.6
   },
   {
    "t": "Tandem",
    "s": 7.6,
    "e": 7.925
   },
   {
    "t": "It",
    "s": 8.325,
    "e": 8.438
   },
   {
    "t": "walks",
    "s": 8.45,
    "e": 8.7
   },
   {
    "t": "the",
    "s": 8.713,
    "e": 8.8
   },
   {
    "t": "route",
    "s": 8.813,
    "e": 9.063
   },
   {
    "t": "before",
    "s": 9.075,
    "e": 9.388
   },
   {
    "t": "you",
    "s": 9.4,
    "e": 9.488
   },
   {
    "t": "do",
    "s": 9.5,
    "e": 9.775
   }
  ]
 }
};
