// Auto-generated by scripts/generate-voiceovers.py. Do not edit.
export type Word = { t: string; s: number; e: number };
export type SceneTiming = { start: number; duration: number; clips: { file: string; start: number }[]; captions: { text: string; s: number; e: number }[]; words: Word[] };
export const CROSSFADE = 0.5;
export const VO_TOTAL = 153.91;
export const TIMING: Record<string, SceneTiming> = {
 "hook": {
  "start": 0.0,
  "duration": 7.26,
  "clips": [
   {
    "file": "audio/hook-0.mp3",
    "start": 1.6
   },
   {
    "file": "audio/hook-1.mp3",
    "start": 4.059
   }
  ],
  "captions": [
   {
    "text": "Your map says nine minutes.",
    "s": 1.7,
    "e": 3.359
   },
   {
    "text": "It doesn't say there are fourteen steps in the way.",
    "s": 4.159,
    "e": 6.355
   }
  ],
  "words": [
   {
    "t": "Your",
    "s": 1.7,
    "e": 1.91
   },
   {
    "t": "map",
    "s": 1.922,
    "e": 2.179
   },
   {
    "t": "says",
    "s": 2.237,
    "e": 2.529
   },
   {
    "t": "nine",
    "s": 2.541,
    "e": 2.892
   },
   {
    "t": "minutes",
    "s": 2.903,
    "e": 3.359
   },
   {
    "t": "It",
    "s": 4.159,
    "e": 4.346
   },
   {
    "t": "doesn't",
    "s": 4.357,
    "e": 4.626
   },
   {
    "t": "say",
    "s": 4.638,
    "e": 4.825
   },
   {
    "t": "there",
    "s": 4.836,
    "e": 4.965
   },
   {
    "t": "are",
    "s": 4.977,
    "e": 5.07
   },
   {
    "t": "fourteen",
    "s": 5.082,
    "e": 5.572
   },
   {
    "t": "steps",
    "s": 5.584,
    "e": 5.888
   },
   {
    "t": "in",
    "s": 5.9,
    "e": 5.958
   },
   {
    "t": "the",
    "s": 5.97,
    "e": 6.04
   },
   {
    "t": "way",
    "s": 6.051,
    "e": 6.355
   }
  ]
 },
 "problem": {
  "start": 6.76,
  "duration": 12.26,
  "clips": [
   {
    "file": "audio/problem-0.mp3",
    "start": 0.6
   },
   {
    "file": "audio/problem-1.mp3",
    "start": 5.286
   },
   {
    "file": "audio/problem-2.mp3",
    "start": 9.761
   }
  ],
  "captions": [
   {
    "text": "A route can look completely valid on a map",
    "s": 0.7,
    "e": 2.779
   },
   {
    "text": "and still be impossible in a wheelchair.",
    "s": 2.978,
    "e": 4.836
   },
   {
    "text": "Maps don't show the stairs, the steep grades, or the broken pavement.",
    "s": 5.386,
    "e": 9.311
   },
   {
    "text": "You find out when you're already there.",
    "s": 9.861,
    "e": 11.356
   }
  ],
  "words": [
   {
    "t": "A",
    "s": 0.7,
    "e": 0.875
   },
   {
    "t": "route",
    "s": 0.887,
    "e": 1.132
   },
   {
    "t": "can",
    "s": 1.144,
    "e": 1.272
   },
   {
    "t": "look",
    "s": 1.284,
    "e": 1.424
   },
   {
    "t": "completely",
    "s": 1.436,
    "e": 1.915
   },
   {
    "t": "valid",
    "s": 1.927,
    "e": 2.242
   },
   {
    "t": "on",
    "s": 2.254,
    "e": 2.382
   },
   {
    "t": "a",
    "s": 2.394,
    "e": 2.417
   },
   {
    "t": "map",
    "s": 2.429,
    "e": 2.779
   },
   {
    "t": "and",
    "s": 2.978,
    "e": 3.153
   },
   {
    "t": "still",
    "s": 3.165,
    "e": 3.434
   },
   {
    "t": "be",
    "s": 3.445,
    "e": 3.539
   },
   {
    "t": "impossible",
    "s": 3.55,
    "e": 4.123
   },
   {
    "t": "in",
    "s": 4.135,
    "e": 4.216
   },
   {
    "t": "a",
    "s": 4.228,
    "e": 4.275
   },
   {
    "t": "wheelchair",
    "s": 4.286,
    "e": 4.836
   },
   {
    "t": "Maps",
    "s": 5.386,
    "e": 5.806
   },
   {
    "t": "don't",
    "s": 5.818,
    "e": 5.993
   },
   {
    "t": "show",
    "s": 6.005,
    "e": 6.203
   },
   {
    "t": "the",
    "s": 6.215,
    "e": 6.297
   },
   {
    "t": "stairs",
    "s": 6.308,
    "e": 6.799
   },
   {
    "t": "the",
    "s": 6.951,
    "e": 7.044
   },
   {
    "t": "steep",
    "s": 7.056,
    "e": 7.395
   },
   {
    "t": "grades",
    "s": 7.407,
    "e": 7.897
   },
   {
    "t": "or",
    "s": 7.979,
    "e": 8.224
   },
   {
    "t": "the",
    "s": 8.248,
    "e": 8.353
   },
   {
    "t": "broken",
    "s": 8.364,
    "e": 8.727
   },
   {
    "t": "pavement",
    "s": 8.738,
    "e": 9.311
   },
   {
    "t": "You",
    "s": 9.861,
    "e": 10.059
   },
   {
    "t": "find",
    "s": 10.071,
    "e": 10.351
   },
   {
    "t": "out",
    "s": 10.363,
    "e": 10.48
   },
   {
    "t": "when",
    "s": 10.492,
    "e": 10.585
   },
   {
    "t": "you're",
    "s": 10.597,
    "e": 10.702
   },
   {
    "t": "already",
    "s": 10.714,
    "e": 11.052
   },
   {
    "t": "there",
    "s": 11.064,
    "e": 11.356
   }
  ]
 },
 "turn": {
  "start": 18.52,
  "duration": 8.96,
  "clips": [
   {
    "file": "audio/turn-0.mp3",
    "start": 1.1
   },
   {
    "file": "audio/turn-1.mp3",
    "start": 5.517
   },
   {
    "file": "audio/turn-2.mp3",
    "start": 6.676
   }
  ],
  "captions": [
   {
    "text": "Tandem walks the route first,",
    "s": 1.2,
    "e": 2.66
   },
   {
    "text": "and checks it for accessibility barriers.",
    "s": 2.894,
    "e": 5.067
   },
   {
    "text": "No new app.",
    "s": 5.617,
    "e": 6.376
   },
   {
    "text": "You just text where you're going.",
    "s": 6.776,
    "e": 8.061
   }
  ],
  "words": [
   {
    "t": "Tandem",
    "s": 1.2,
    "e": 1.656
   },
   {
    "t": "walks",
    "s": 1.667,
    "e": 1.924
   },
   {
    "t": "the",
    "s": 1.936,
    "e": 2.029
   },
   {
    "t": "route",
    "s": 2.041,
    "e": 2.24
   },
   {
    "t": "first",
    "s": 2.251,
    "e": 2.66
   },
   {
    "t": "and",
    "s": 2.894,
    "e": 3.046
   },
   {
    "t": "checks",
    "s": 3.081,
    "e": 3.35
   },
   {
    "t": "it",
    "s": 3.361,
    "e": 3.513
   },
   {
    "t": "for",
    "s": 3.525,
    "e": 3.642
   },
   {
    "t": "accessibility",
    "s": 3.653,
    "e": 4.413
   },
   {
    "t": "barriers",
    "s": 4.424,
    "e": 5.067
   },
   {
    "t": "No",
    "s": 5.617,
    "e": 5.886
   },
   {
    "t": "new",
    "s": 5.897,
    "e": 6.049
   },
   {
    "t": "app.",
    "s": 6.061,
    "e": 6.376
   },
   {
    "t": "You",
    "s": 6.776,
    "e": 6.975
   },
   {
    "t": "just",
    "s": 6.986,
    "e": 7.15
   },
   {
    "t": "text",
    "s": 7.162,
    "e": 7.43
   },
   {
    "t": "where",
    "s": 7.442,
    "e": 7.559
   },
   {
    "t": "you're",
    "s": 7.571,
    "e": 7.676
   },
   {
    "t": "going",
    "s": 7.687,
    "e": 8.061
   }
  ]
 },
 "request": {
  "start": 26.98,
  "duration": 7.28,
  "clips": [
   {
    "file": "audio/request-0.mp3",
    "start": 0.6
   }
  ],
  "captions": [
   {
    "text": "You tell it where you're headed and how you get around,",
    "s": 0.7,
    "e": 2.861
   },
   {
    "text": "the same way you'd text a friend.",
    "s": 3.212,
    "e": 4.882
   }
  ],
  "words": [
   {
    "t": "You",
    "s": 0.7,
    "e": 0.864
   },
   {
    "t": "tell",
    "s": 0.875,
    "e": 1.086
   },
   {
    "t": "it",
    "s": 1.097,
    "e": 1.179
   },
   {
    "t": "where",
    "s": 1.191,
    "e": 1.319
   },
   {
    "t": "you're",
    "s": 1.331,
    "e": 1.448
   },
   {
    "t": "headed",
    "s": 1.459,
    "e": 1.821
   },
   {
    "t": "and",
    "s": 1.845,
    "e": 1.985
   },
   {
    "t": "how",
    "s": 1.997,
    "e": 2.125
   },
   {
    "t": "you",
    "s": 2.137,
    "e": 2.254
   },
   {
    "t": "get",
    "s": 2.265,
    "e": 2.429
   },
   {
    "t": "around",
    "s": 2.441,
    "e": 2.861
   },
   {
    "t": "the",
    "s": 3.212,
    "e": 3.305
   },
   {
    "t": "same",
    "s": 3.317,
    "e": 3.667
   },
   {
    "t": "way",
    "s": 3.679,
    "e": 3.854
   },
   {
    "t": "you'd",
    "s": 3.866,
    "e": 4.041
   },
   {
    "t": "text",
    "s": 4.053,
    "e": 4.345
   },
   {
    "t": "a",
    "s": 4.357,
    "e": 4.403
   },
   {
    "t": "friend",
    "s": 4.415,
    "e": 4.882
   }
  ]
 },
 "scout": {
  "start": 33.76,
  "duration": 24.24,
  "clips": [
   {
    "file": "audio/scout-0.mp3",
    "start": 1.6
   },
   {
    "file": "audio/scout-1.mp3",
    "start": 8.398
   },
   {
    "file": "audio/scout-2.mp3",
    "start": 9.424
   },
   {
    "file": "audio/scout-3.mp3",
    "start": 10.45
   },
   {
    "file": "audio/scout-4.mp3",
    "start": 12.375
   },
   {
    "file": "audio/scout-5.mp3",
    "start": 14.426
   },
   {
    "file": "audio/scout-6.mp3",
    "start": 17.427
   }
  ],
  "captions": [
   {
    "text": "Tandem samples Street View along each candidate route,",
    "s": 1.7,
    "e": 4.656
   },
   {
    "text": "and checks every photo for barriers to a wheelchair.",
    "s": 5.053,
    "e": 7.798
   },
   {
    "text": "Clear.",
    "s": 8.498,
    "e": 9.024
   },
   {
    "text": "Clear.",
    "s": 9.524,
    "e": 10.05
   },
   {
    "text": "Clear.",
    "s": 10.55,
    "e": 11.075
   },
   {
    "text": "Then, fourteen steps.",
    "s": 12.475,
    "e": 14.076
   },
   {
    "text": "No ramp.",
    "s": 14.526,
    "e": 15.227
   },
   {
    "text": "It also checks signals like elevation,",
    "s": 17.527,
    "e": 19.618
   },
   {
    "text": "so it can show you the tradeoffs instead of hiding them.",
    "s": 19.992,
    "e": 22.644
   }
  ],
  "words": [
   {
    "t": "Tandem",
    "s": 1.7,
    "e": 2.144
   },
   {
    "t": "samples",
    "s": 2.156,
    "e": 2.6
   },
   {
    "t": "Street",
    "s": 2.611,
    "e": 2.88
   },
   {
    "t": "View",
    "s": 2.892,
    "e": 3.184
   },
   {
    "t": "along",
    "s": 3.207,
    "e": 3.593
   },
   {
    "t": "each",
    "s": 3.616,
    "e": 3.838
   },
   {
    "t": "candidate",
    "s": 3.85,
    "e": 4.364
   },
   {
    "t": "route",
    "s": 4.375,
    "e": 4.656
   },
   {
    "t": "and",
    "s": 5.053,
    "e": 5.205
   },
   {
    "t": "checks",
    "s": 5.275,
    "e": 5.567
   },
   {
    "t": "every",
    "s": 5.672,
    "e": 5.882
   },
   {
    "t": "photo",
    "s": 5.894,
    "e": 6.291
   },
   {
    "t": "for",
    "s": 6.303,
    "e": 6.455
   },
   {
    "t": "barriers",
    "s": 6.466,
    "e": 7.015
   },
   {
    "t": "to",
    "s": 7.027,
    "e": 7.144
   },
   {
    "t": "a",
    "s": 7.156,
    "e": 7.214
   },
   {
    "t": "wheelchair",
    "s": 7.226,
    "e": 7.798
   },
   {
    "t": "Clear",
    "s": 8.498,
    "e": 9.024
   },
   {
    "t": "Clear",
    "s": 9.524,
    "e": 10.05
   },
   {
    "t": "Clear",
    "s": 10.55,
    "e": 11.075
   },
   {
    "t": "Then",
    "s": 12.475,
    "e": 12.872
   },
   {
    "t": "fourteen",
    "s": 13.118,
    "e": 13.573
   },
   {
    "t": "steps",
    "s": 13.585,
    "e": 14.076
   },
   {
    "t": "No",
    "s": 14.526,
    "e": 14.818
   },
   {
    "t": "ramp",
    "s": 14.829,
    "e": 15.227
   },
   {
    "t": "It",
    "s": 17.527,
    "e": 17.702
   },
   {
    "t": "also",
    "s": 17.714,
    "e": 17.971
   },
   {
    "t": "checks",
    "s": 17.982,
    "e": 18.263
   },
   {
    "t": "signals",
    "s": 18.274,
    "e": 18.66
   },
   {
    "t": "like",
    "s": 18.672,
    "e": 18.894
   },
   {
    "t": "elevation",
    "s": 19.01,
    "e": 19.618
   },
   {
    "t": "so",
    "s": 19.992,
    "e": 20.249
   },
   {
    "t": "it",
    "s": 20.272,
    "e": 20.365
   },
   {
    "t": "can",
    "s": 20.377,
    "e": 20.529
   },
   {
    "t": "show",
    "s": 20.541,
    "e": 20.751
   },
   {
    "t": "you",
    "s": 20.763,
    "e": 20.868
   },
   {
    "t": "the",
    "s": 20.879,
    "e": 20.961
   },
   {
    "t": "tradeoffs",
    "s": 20.973,
    "e": 21.534
   },
   {
    "t": "instead",
    "s": 21.545,
    "e": 21.966
   },
   {
    "t": "of",
    "s": 21.978,
    "e": 22.048
   },
   {
    "t": "hiding",
    "s": 22.059,
    "e": 22.328
   },
   {
    "t": "them",
    "s": 22.34,
    "e": 22.644
   }
  ]
 },
 "reply": {
  "start": 57.5,
  "duration": 41.55,
  "clips": [
   {
    "file": "audio/reply-0.mp3",
    "start": 0.9
   },
   {
    "file": "audio/reply-1.mp3",
    "start": 3.93
   },
   {
    "file": "audio/reply-2.mp3",
    "start": 9.329
   },
   {
    "file": "audio/reply-3.mp3",
    "start": 14.225
   },
   {
    "file": "audio/reply-4.mp3",
    "start": 16.688
   },
   {
    "file": "audio/reply-5.mp3",
    "start": 21.466
   },
   {
    "file": "audio/reply-6.mp3",
    "start": 25.339
   },
   {
    "file": "audio/reply-7.mp3",
    "start": 31.356
   },
   {
    "file": "audio/reply-8.mp3",
    "start": 33.57
   },
   {
    "file": "audio/reply-9.mp3",
    "start": 37.227
   }
  ],
  "captions": [
   {
    "text": "About a minute later, Tandem texts you back.",
    "s": 1.0,
    "e": 3.43
   },
   {
    "text": "A map of what it found.",
    "s": 4.03,
    "e": 5.455
   },
   {
    "text": "The photo it flagged, and when that photo was taken.",
    "s": 5.791,
    "e": 8.629
   },
   {
    "text": "Google Maps' route takes 9.4 minutes,",
    "s": 9.429,
    "e": 11.918
   },
   {
    "text": "and runs straight into the stairs.",
    "s": 12.128,
    "e": 13.775
   },
   {
    "text": "Tandem's takes 9.5.",
    "s": 14.325,
    "e": 16.288
   },
   {
    "text": "It avoids the staircase,",
    "s": 16.788,
    "e": 18.12
   },
   {
    "text": "while still warning you about the steep climb ahead.",
    "s": 18.236,
    "e": 20.666
   },
   {
    "text": "It checks the last twenty meters too: the doors of the building.",
    "s": 21.566,
    "e": 24.989
   },
   {
    "text": "Here, the map doesn't say which one is step-free,",
    "s": 25.439,
    "e": 27.986
   },
   {
    "text": "so Tandem tells you that, instead of guessing.",
    "s": 28.208,
    "e": 30.556
   },
   {
    "text": "It checks the weather for when you're leaving.",
    "s": 31.456,
    "e": 33.22
   },
   {
    "text": "If that climb will be icy, it offers the bus instead.",
    "s": 33.67,
    "e": 36.427
   },
   {
    "text": "And it sends the whole walk, so you can see it before you take it.",
    "s": 37.327,
    "e": 40.248
   }
  ],
  "words": [
   {
    "t": "About",
    "s": 1.0,
    "e": 1.327
   },
   {
    "t": "a",
    "s": 1.339,
    "e": 1.374
   },
   {
    "t": "minute",
    "s": 1.385,
    "e": 1.643
   },
   {
    "t": "later",
    "s": 1.654,
    "e": 2.005
   },
   {
    "t": "Tandem",
    "s": 2.215,
    "e": 2.624
   },
   {
    "t": "texts",
    "s": 2.635,
    "e": 2.928
   },
   {
    "t": "you",
    "s": 2.939,
    "e": 3.033
   },
   {
    "t": "back",
    "s": 3.044,
    "e": 3.43
   },
   {
    "t": "A",
    "s": 4.03,
    "e": 4.17
   },
   {
    "t": "map",
    "s": 4.182,
    "e": 4.497
   },
   {
    "t": "of",
    "s": 4.544,
    "e": 4.696
   },
   {
    "t": "what",
    "s": 4.707,
    "e": 4.836
   },
   {
    "t": "it",
    "s": 4.848,
    "e": 4.941
   },
   {
    "t": "found",
    "s": 4.953,
    "e": 5.455
   },
   {
    "t": "The",
    "s": 5.791,
    "e": 5.966
   },
   {
    "t": "photo",
    "s": 5.978,
    "e": 6.351
   },
   {
    "t": "it",
    "s": 6.363,
    "e": 6.468
   },
   {
    "t": "flagged",
    "s": 6.48,
    "e": 7.029
   },
   {
    "t": "and",
    "s": 7.087,
    "e": 7.333
   },
   {
    "t": "when",
    "s": 7.344,
    "e": 7.473
   },
   {
    "t": "that",
    "s": 7.485,
    "e": 7.648
   },
   {
    "t": "photo",
    "s": 7.66,
    "e": 7.987
   },
   {
    "t": "was",
    "s": 7.999,
    "e": 8.139
   },
   {
    "t": "taken",
    "s": 8.15,
    "e": 8.629
   },
   {
    "t": "Google",
    "s": 9.429,
    "e": 9.756
   },
   {
    "t": "Maps'",
    "s": 9.768,
    "e": 10.107
   },
   {
    "t": "route",
    "s": 10.119,
    "e": 10.352
   },
   {
    "t": "takes",
    "s": 10.364,
    "e": 10.633
   },
   {
    "t": "nine",
    "s": 10.644,
    "e": 10.995
   },
   {
    "t": "point",
    "s": 11.006,
    "e": 11.287
   },
   {
    "t": "four",
    "s": 11.299,
    "e": 11.52
   },
   {
    "t": "minutes",
    "s": 11.532,
    "e": 11.918
   },
   {
    "t": "and",
    "s": 12.128,
    "e": 12.291
   },
   {
    "t": "runs",
    "s": 12.303,
    "e": 12.607
   },
   {
    "t": "straight",
    "s": 12.619,
    "e": 12.969
   },
   {
    "t": "into",
    "s": 12.981,
    "e": 13.133
   },
   {
    "t": "the",
    "s": 13.144,
    "e": 13.226
   },
   {
    "t": "stairs",
    "s": 13.238,
    "e": 13.775
   },
   {
    "t": "Tandem's",
    "s": 14.325,
    "e": 14.898
   },
   {
    "t": "takes",
    "s": 14.909,
    "e": 15.178
   },
   {
    "t": "nine",
    "s": 15.19,
    "e": 15.54
   },
   {
    "t": "point",
    "s": 15.552,
    "e": 15.785
   },
   {
    "t": "five",
    "s": 15.797,
    "e": 16.288
   },
   {
    "t": "It",
    "s": 16.788,
    "e": 16.951
   },
   {
    "t": "avoids",
    "s": 16.963,
    "e": 17.337
   },
   {
    "t": "the",
    "s": 17.349,
    "e": 17.442
   },
   {
    "t": "staircase",
    "s": 17.454,
    "e": 18.12
   },
   {
    "t": "while",
    "s": 18.236,
    "e": 18.47
   },
   {
    "t": "still",
    "s": 18.482,
    "e": 18.832
   },
   {
    "t": "warning",
    "s": 18.844,
    "e": 19.148
   },
   {
    "t": "you",
    "s": 19.159,
    "e": 19.299
   },
   {
    "t": "about",
    "s": 19.311,
    "e": 19.533
   },
   {
    "t": "the",
    "s": 19.545,
    "e": 19.638
   },
   {
    "t": "steep",
    "s": 19.65,
    "e": 20.0
   },
   {
    "t": "climb",
    "s": 20.012,
    "e": 20.304
   },
   {
    "t": "ahead",
    "s": 20.316,
    "e": 20.666
   },
   {
    "t": "It",
    "s": 21.566,
    "e": 21.753
   },
   {
    "t": "checks",
    "s": 21.765,
    "e": 22.022
   },
   {
    "t": "the",
    "s": 22.034,
    "e": 22.15
   },
   {
    "t": "last",
    "s": 22.162,
    "e": 22.548
   },
   {
    "t": "twenty",
    "s": 22.559,
    "e": 22.793
   },
   {
    "t": "meters",
    "s": 22.805,
    "e": 23.167
   },
   {
    "t": "too",
    "s": 23.178,
    "e": 23.459
   },
   {
    "t": "the",
    "s": 23.833,
    "e": 23.961
   },
   {
    "t": "doors",
    "s": 23.973,
    "e": 24.3
   },
   {
    "t": "of",
    "s": 24.312,
    "e": 24.382
   },
   {
    "t": "the",
    "s": 24.393,
    "e": 24.463
   },
   {
    "t": "building",
    "s": 24.475,
    "e": 24.989
   },
   {
    "t": "Here",
    "s": 25.439,
    "e": 25.871
   },
   {
    "t": "the",
    "s": 26.128,
    "e": 26.21
   },
   {
    "t": "map",
    "s": 26.222,
    "e": 26.502
   },
   {
    "t": "doesn't",
    "s": 26.514,
    "e": 26.794
   },
   {
    "t": "say",
    "s": 26.806,
    "e": 26.993
   },
   {
    "t": "which",
    "s": 27.005,
    "e": 27.203
   },
   {
    "t": "one",
    "s": 27.215,
    "e": 27.355
   },
   {
    "t": "is",
    "s": 27.367,
    "e": 27.46
   },
   {
    "t": "step-free",
    "s": 27.472,
    "e": 27.986
   },
   {
    "t": "so",
    "s": 28.208,
    "e": 28.371
   },
   {
    "t": "Tandem",
    "s": 28.383,
    "e": 28.78
   },
   {
    "t": "tells",
    "s": 28.792,
    "e": 29.049
   },
   {
    "t": "you",
    "s": 29.061,
    "e": 29.142
   },
   {
    "t": "that",
    "s": 29.154,
    "e": 29.423
   },
   {
    "t": "instead",
    "s": 29.528,
    "e": 29.96
   },
   {
    "t": "of",
    "s": 29.972,
    "e": 30.054
   },
   {
    "t": "guessing",
    "s": 30.065,
    "e": 30.556
   },
   {
    "t": "It",
    "s": 31.456,
    "e": 31.655
   },
   {
    "t": "checks",
    "s": 31.666,
    "e": 31.935
   },
   {
    "t": "the",
    "s": 31.947,
    "e": 32.063
   },
   {
    "t": "weather",
    "s": 32.075,
    "e": 32.367
   },
   {
    "t": "for",
    "s": 32.379,
    "e": 32.531
   },
   {
    "t": "when",
    "s": 32.542,
    "e": 32.648
   },
   {
    "t": "you're",
    "s": 32.659,
    "e": 32.764
   },
   {
    "t": "leaving",
    "s": 32.776,
    "e": 33.22
   },
   {
    "t": "If",
    "s": 33.67,
    "e": 33.88
   },
   {
    "t": "that",
    "s": 33.892,
    "e": 34.067
   },
   {
    "t": "climb",
    "s": 34.079,
    "e": 34.359
   },
   {
    "t": "will",
    "s": 34.371,
    "e": 34.476
   },
   {
    "t": "be",
    "s": 34.488,
    "e": 34.605
   },
   {
    "t": "icy",
    "s": 34.616,
    "e": 35.06
   },
   {
    "t": "it",
    "s": 35.107,
    "e": 35.177
   },
   {
    "t": "offers",
    "s": 35.189,
    "e": 35.563
   },
   {
    "t": "the",
    "s": 35.574,
    "e": 35.679
   },
   {
    "t": "bus",
    "s": 35.691,
    "e": 35.913
   },
   {
    "t": "instead",
    "s": 35.925,
    "e": 36.427
   },
   {
    "t": "And",
    "s": 37.327,
    "e": 37.607
   },
   {
    "t": "it",
    "s": 37.619,
    "e": 37.712
   },
   {
    "t": "sends",
    "s": 37.724,
    "e": 37.97
   },
   {
    "t": "the",
    "s": 37.981,
    "e": 38.075
   },
   {
    "t": "whole",
    "s": 38.086,
    "e": 38.273
   },
   {
    "t": "walk",
    "s": 38.285,
    "e": 38.6
   },
   {
    "t": "so",
    "s": 38.694,
    "e": 38.811
   },
   {
    "t": "you",
    "s": 38.822,
    "e": 38.904
   },
   {
    "t": "can",
    "s": 38.916,
    "e": 39.068
   },
   {
    "t": "see",
    "s": 39.079,
    "e": 39.231
   },
   {
    "t": "it",
    "s": 39.243,
    "e": 39.36
   },
   {
    "t": "before",
    "s": 39.371,
    "e": 39.663
   },
   {
    "t": "you",
    "s": 39.675,
    "e": 39.757
   },
   {
    "t": "take",
    "s": 39.769,
    "e": 39.979
   },
   {
    "t": "it",
    "s": 39.991,
    "e": 40.248
   }
  ]
 },
 "memory": {
  "start": 98.55,
  "duration": 11.96,
  "clips": [
   {
    "file": "audio/memory-0.mp3",
    "start": 0.8
   },
   {
    "file": "audio/memory-1.mp3",
    "start": 4.11
   }
  ],
  "captions": [
   {
    "text": "When you arrive, you can tell Tandem what it missed.",
    "s": 0.9,
    "e": 3.61
   },
   {
    "text": "Every scout and every report lands on a shared campus barrier map,",
    "s": 4.21,
    "e": 8.287
   },
   {
    "text": "so the next person starts with what you found.",
    "s": 8.696,
    "e": 10.963
   }
  ],
  "words": [
   {
    "t": "When",
    "s": 0.9,
    "e": 1.087
   },
   {
    "t": "you",
    "s": 1.099,
    "e": 1.192
   },
   {
    "t": "arrive",
    "s": 1.204,
    "e": 1.741
   },
   {
    "t": "you",
    "s": 2.022,
    "e": 2.103
   },
   {
    "t": "can",
    "s": 2.115,
    "e": 2.255
   },
   {
    "t": "tell",
    "s": 2.267,
    "e": 2.454
   },
   {
    "t": "Tandem",
    "s": 2.465,
    "e": 2.909
   },
   {
    "t": "what",
    "s": 2.921,
    "e": 3.038
   },
   {
    "t": "it",
    "s": 3.05,
    "e": 3.12
   },
   {
    "t": "missed",
    "s": 3.131,
    "e": 3.61
   },
   {
    "t": "Every",
    "s": 4.21,
    "e": 4.537
   },
   {
    "t": "scout",
    "s": 4.549,
    "e": 4.935
   },
   {
    "t": "and",
    "s": 5.028,
    "e": 5.192
   },
   {
    "t": "every",
    "s": 5.332,
    "e": 5.612
   },
   {
    "t": "report",
    "s": 5.624,
    "e": 6.044
   },
   {
    "t": "lands",
    "s": 6.056,
    "e": 6.453
   },
   {
    "t": "on",
    "s": 6.488,
    "e": 6.617
   },
   {
    "t": "a",
    "s": 6.628,
    "e": 6.663
   },
   {
    "t": "shared",
    "s": 6.675,
    "e": 7.142
   },
   {
    "t": "campus",
    "s": 7.154,
    "e": 7.575
   },
   {
    "t": "barrier",
    "s": 7.586,
    "e": 7.972
   },
   {
    "t": "map",
    "s": 7.984,
    "e": 8.287
   },
   {
    "t": "so",
    "s": 8.696,
    "e": 8.801
   },
   {
    "t": "the",
    "s": 8.813,
    "e": 8.906
   },
   {
    "t": "next",
    "s": 8.918,
    "e": 9.234
   },
   {
    "t": "person",
    "s": 9.245,
    "e": 9.584
   },
   {
    "t": "starts",
    "s": 9.596,
    "e": 10.051
   },
   {
    "t": "with",
    "s": 10.063,
    "e": 10.192
   },
   {
    "t": "what",
    "s": 10.203,
    "e": 10.343
   },
   {
    "t": "you",
    "s": 10.355,
    "e": 10.449
   },
   {
    "t": "found",
    "s": 10.46,
    "e": 10.963
   }
  ]
 },
 "night": {
  "start": 110.01,
  "duration": 14.87,
  "clips": [
   {
    "file": "audio/night-0.mp3",
    "start": 0.9
   },
   {
    "file": "audio/night-1.mp3",
    "start": 2.416
   },
   {
    "file": "audio/night-2.mp3",
    "start": 8.799
   },
   {
    "file": "audio/night-3.mp3",
    "start": 11.983
   }
  ],
  "captions": [
   {
    "text": "Walking alone at night?",
    "s": 1.0,
    "e": 2.016
   },
   {
    "text": "Tandem checks the same routes for street lights, isolated stretches,",
    "s": 2.516,
    "e": 6.336
   },
   {
    "text": "and blue-light emergency phones.",
    "s": 6.465,
    "e": 8.299
   },
   {
    "text": "Here, 2% of Google's route is mapped as lit.",
    "s": 8.899,
    "e": 11.633
   },
   {
    "text": "The alternative: 33%.",
    "s": 12.083,
    "e": 13.87
   }
  ],
  "words": [
   {
    "t": "Walking",
    "s": 1.0,
    "e": 1.362
   },
   {
    "t": "alone",
    "s": 1.374,
    "e": 1.596
   },
   {
    "t": "at",
    "s": 1.607,
    "e": 1.689
   },
   {
    "t": "night",
    "s": 1.701,
    "e": 2.016
   },
   {
    "t": "Tandem",
    "s": 2.516,
    "e": 2.949
   },
   {
    "t": "checks",
    "s": 2.96,
    "e": 3.217
   },
   {
    "t": "the",
    "s": 3.229,
    "e": 3.334
   },
   {
    "t": "same",
    "s": 3.346,
    "e": 3.708
   },
   {
    "t": "routes",
    "s": 3.72,
    "e": 4.012
   },
   {
    "t": "for",
    "s": 4.023,
    "e": 4.163
   },
   {
    "t": "street",
    "s": 4.175,
    "e": 4.479
   },
   {
    "t": "lights",
    "s": 4.491,
    "e": 4.876
   },
   {
    "t": "isolated",
    "s": 5.215,
    "e": 5.729
   },
   {
    "t": "stretches",
    "s": 5.741,
    "e": 6.336
   },
   {
    "t": "and",
    "s": 6.465,
    "e": 6.699
   },
   {
    "t": "blue-light",
    "s": 6.71,
    "e": 7.224
   },
   {
    "t": "emergency",
    "s": 7.236,
    "e": 7.727
   },
   {
    "t": "phones",
    "s": 7.738,
    "e": 8.299
   },
   {
    "t": "Here",
    "s": 8.899,
    "e": 9.401
   },
   {
    "t": "two",
    "s": 9.495,
    "e": 9.658
   },
   {
    "t": "percent",
    "s": 9.67,
    "e": 10.009
   },
   {
    "t": "of",
    "s": 10.021,
    "e": 10.102
   },
   {
    "t": "Google's",
    "s": 10.114,
    "e": 10.464
   },
   {
    "t": "route",
    "s": 10.476,
    "e": 10.745
   },
   {
    "t": "is",
    "s": 10.756,
    "e": 10.885
   },
   {
    "t": "mapped",
    "s": 10.897,
    "e": 11.189
   },
   {
    "t": "as",
    "s": 11.2,
    "e": 11.329
   },
   {
    "t": "lit",
    "s": 11.341,
    "e": 11.633
   },
   {
    "t": "The",
    "s": 12.083,
    "e": 12.246
   },
   {
    "t": "alternative",
    "s": 12.258,
    "e": 12.877
   },
   {
    "t": "thirty-three",
    "s": 13.216,
    "e": 13.87
   }
  ]
 },
 "more": {
  "start": 124.38,
  "duration": 15.17,
  "clips": [
   {
    "file": "audio/more-0.mp3",
    "start": 0.8
   },
   {
    "file": "audio/more-1.mp3",
    "start": 2.141
   },
   {
    "file": "audio/more-2.mp3",
    "start": 5.8
   },
   {
    "file": "audio/more-3.mp3",
    "start": 9.463
   }
  ],
  "captions": [
   {
    "text": "And there's more.",
    "s": 0.9,
    "e": 1.741
   },
   {
    "text": "A trip page with every detail. A stroller mode.",
    "s": 2.241,
    "e": 5.45
   },
   {
    "text": "You can drop a pin to start, and it remembers how you get around.",
    "s": 5.9,
    "e": 9.113
   },
   {
    "text": "At night, it shows what's open late.",
    "s": 9.563,
    "e": 11.537
   },
   {
    "text": "And it always says which stretch it couldn't check.",
    "s": 11.873,
    "e": 14.174
   }
  ],
  "words": [
   {
    "t": "And",
    "s": 0.9,
    "e": 1.099
   },
   {
    "t": "there's",
    "s": 1.145,
    "e": 1.356
   },
   {
    "t": "more",
    "s": 1.367,
    "e": 1.741
   },
   {
    "t": "A",
    "s": 2.241,
    "e": 2.405
   },
   {
    "t": "trip",
    "s": 2.416,
    "e": 2.72
   },
   {
    "t": "page",
    "s": 2.732,
    "e": 3.094
   },
   {
    "t": "with",
    "s": 3.106,
    "e": 3.246
   },
   {
    "t": "every",
    "s": 3.328,
    "e": 3.585
   },
   {
    "t": "detail",
    "s": 3.596,
    "e": 4.145
   },
   {
    "t": "A",
    "s": 4.481,
    "e": 4.633
   },
   {
    "t": "stroller",
    "s": 4.644,
    "e": 5.053
   },
   {
    "t": "mode",
    "s": 5.065,
    "e": 5.45
   },
   {
    "t": "You",
    "s": 5.9,
    "e": 6.041
   },
   {
    "t": "can",
    "s": 6.052,
    "e": 6.157
   },
   {
    "t": "drop",
    "s": 6.169,
    "e": 6.403
   },
   {
    "t": "a",
    "s": 6.414,
    "e": 6.473
   },
   {
    "t": "pin",
    "s": 6.485,
    "e": 6.718
   },
   {
    "t": "to",
    "s": 6.73,
    "e": 6.812
   },
   {
    "t": "start",
    "s": 6.823,
    "e": 7.197
   },
   {
    "t": "and",
    "s": 7.442,
    "e": 7.629
   },
   {
    "t": "it",
    "s": 7.653,
    "e": 7.735
   },
   {
    "t": "remembers",
    "s": 7.746,
    "e": 8.214
   },
   {
    "t": "how",
    "s": 8.225,
    "e": 8.33
   },
   {
    "t": "you",
    "s": 8.342,
    "e": 8.459
   },
   {
    "t": "get",
    "s": 8.471,
    "e": 8.599
   },
   {
    "t": "around",
    "s": 8.611,
    "e": 9.113
   },
   {
    "t": "At",
    "s": 9.563,
    "e": 9.785
   },
   {
    "t": "night",
    "s": 9.797,
    "e": 10.135
   },
   {
    "t": "it",
    "s": 10.287,
    "e": 10.381
   },
   {
    "t": "shows",
    "s": 10.393,
    "e": 10.766
   },
   {
    "t": "what's",
    "s": 10.778,
    "e": 10.953
   },
   {
    "t": "open",
    "s": 10.965,
    "e": 11.222
   },
   {
    "t": "late",
    "s": 11.234,
    "e": 11.537
   },
   {
    "t": "And",
    "s": 11.873,
    "e": 12.165
   },
   {
    "t": "it",
    "s": 12.2,
    "e": 12.258
   },
   {
    "t": "always",
    "s": 12.27,
    "e": 12.621
   },
   {
    "t": "says",
    "s": 12.632,
    "e": 12.924
   },
   {
    "t": "which",
    "s": 12.936,
    "e": 13.135
   },
   {
    "t": "stretch",
    "s": 13.146,
    "e": 13.45
   },
   {
    "t": "it",
    "s": 13.462,
    "e": 13.555
   },
   {
    "t": "couldn't",
    "s": 13.567,
    "e": 13.824
   },
   {
    "t": "check",
    "s": 13.835,
    "e": 14.174
   }
  ]
 },
 "closing": {
  "start": 139.05,
  "duration": 10.85,
  "clips": [
   {
    "file": "audio/closing-0.mp3",
    "start": 0.7
   },
   {
    "file": "audio/closing-1.mp3",
    "start": 3.645
   },
   {
    "file": "audio/closing-2.mp3",
    "start": 7.051
   },
   {
    "file": "audio/closing-3.mp3",
    "start": 8.012
   }
  ],
  "captions": [
   {
    "text": "Navigation shouldn't just know where a path goes.",
    "s": 0.8,
    "e": 3.195
   },
   {
    "text": "It should tell you whether that path is accessible to you.",
    "s": 3.745,
    "e": 6.151
   },
   {
    "text": "Tandem.",
    "s": 7.151,
    "e": 7.712
   },
   {
    "text": "It walks the route before you do.",
    "s": 8.112,
    "e": 9.654
   }
  ],
  "words": [
   {
    "t": "Navigation",
    "s": 0.8,
    "e": 1.524
   },
   {
    "t": "shouldn't",
    "s": 1.536,
    "e": 1.84
   },
   {
    "t": "just",
    "s": 1.851,
    "e": 2.062
   },
   {
    "t": "know",
    "s": 2.073,
    "e": 2.26
   },
   {
    "t": "where",
    "s": 2.272,
    "e": 2.4
   },
   {
    "t": "a",
    "s": 2.412,
    "e": 2.459
   },
   {
    "t": "path",
    "s": 2.471,
    "e": 2.763
   },
   {
    "t": "goes",
    "s": 2.774,
    "e": 3.195
   },
   {
    "t": "It",
    "s": 3.745,
    "e": 3.92
   },
   {
    "t": "should",
    "s": 3.932,
    "e": 4.095
   },
   {
    "t": "tell",
    "s": 4.107,
    "e": 4.282
   },
   {
    "t": "you",
    "s": 4.294,
    "e": 4.387
   },
   {
    "t": "whether",
    "s": 4.399,
    "e": 4.621
   },
   {
    "t": "that",
    "s": 4.633,
    "e": 4.773
   },
   {
    "t": "path",
    "s": 4.785,
    "e": 5.147
   },
   {
    "t": "is",
    "s": 5.158,
    "e": 5.24
   },
   {
    "t": "accessible",
    "s": 5.252,
    "e": 5.789
   },
   {
    "t": "to",
    "s": 5.801,
    "e": 5.894
   },
   {
    "t": "you",
    "s": 5.906,
    "e": 6.151
   },
   {
    "t": "Tandem",
    "s": 7.151,
    "e": 7.712
   },
   {
    "t": "It",
    "s": 8.112,
    "e": 8.276
   },
   {
    "t": "walks",
    "s": 8.287,
    "e": 8.556
   },
   {
    "t": "the",
    "s": 8.568,
    "e": 8.661
   },
   {
    "t": "route",
    "s": 8.673,
    "e": 8.848
   },
   {
    "t": "before",
    "s": 8.86,
    "e": 9.152
   },
   {
    "t": "you",
    "s": 9.164,
    "e": 9.257
   },
   {
    "t": "do",
    "s": 9.269,
    "e": 9.654
   }
  ]
 },
 "live": {
  "start": 149.4,
  "duration": 4.51,
  "clips": [
   {
    "file": "audio/live-0.mp3",
    "start": 0.9
   }
  ],
  "captions": [
   {
    "text": "Now, watch it work for real.",
    "s": 1.0,
    "e": 2.706
   }
  ],
  "words": [
   {
    "t": "Now",
    "s": 1.0,
    "e": 1.572
   },
   {
    "t": "watch",
    "s": 1.631,
    "e": 1.864
   },
   {
    "t": "it",
    "s": 1.876,
    "e": 1.97
   },
   {
    "t": "work",
    "s": 1.981,
    "e": 2.168
   },
   {
    "t": "for",
    "s": 2.18,
    "e": 2.332
   },
   {
    "t": "real",
    "s": 2.343,
    "e": 2.706
   }
  ]
 }
};
