// Auto-generated by scripts/generate-voiceovers.py. Do not edit.
export type Word = { t: string; s: number; e: number };
export type SceneTiming = { start: number; duration: number; clips: { file: string; start: number }[]; captions: { text: string; s: number; e: number }[]; words: Word[] };
export const CROSSFADE = 0.5;
export const VO_TOTAL = 90.71;
export const TIMING: Record<string, SceneTiming> = {
 "hook": {
  "start": 0.0,
  "duration": 7.26,
  "clips": [
   {
    "file": "audio/hook-0.mp3",
    "start": 1.6
   },
   {
    "file": "audio/hook-1.mp3",
    "start": 4.059
   }
  ],
  "captions": [
   {
    "text": "Your map says nine minutes.",
    "s": 1.7,
    "e": 3.359
   },
   {
    "text": "It doesn't say there are fourteen steps in the way.",
    "s": 4.159,
    "e": 6.355
   }
  ],
  "words": [
   {
    "t": "Your",
    "s": 1.7,
    "e": 1.91
   },
   {
    "t": "map",
    "s": 1.922,
    "e": 2.179
   },
   {
    "t": "says",
    "s": 2.237,
    "e": 2.529
   },
   {
    "t": "nine",
    "s": 2.541,
    "e": 2.892
   },
   {
    "t": "minutes",
    "s": 2.903,
    "e": 3.359
   },
   {
    "t": "It",
    "s": 4.159,
    "e": 4.346
   },
   {
    "t": "doesn't",
    "s": 4.357,
    "e": 4.626
   },
   {
    "t": "say",
    "s": 4.638,
    "e": 4.825
   },
   {
    "t": "there",
    "s": 4.836,
    "e": 4.965
   },
   {
    "t": "are",
    "s": 4.977,
    "e": 5.07
   },
   {
    "t": "fourteen",
    "s": 5.082,
    "e": 5.572
   },
   {
    "t": "steps",
    "s": 5.584,
    "e": 5.888
   },
   {
    "t": "in",
    "s": 5.9,
    "e": 5.958
   },
   {
    "t": "the",
    "s": 5.97,
    "e": 6.04
   },
   {
    "t": "way",
    "s": 6.051,
    "e": 6.355
   }
  ]
 },
 "problem": {
  "start": 6.76,
  "duration": 12.26,
  "clips": [
   {
    "file": "audio/problem-0.mp3",
    "start": 0.6
   },
   {
    "file": "audio/problem-1.mp3",
    "start": 5.286
   },
   {
    "file": "audio/problem-2.mp3",
    "start": 9.761
   }
  ],
  "captions": [
   {
    "text": "A route can look completely valid on a map",
    "s": 0.7,
    "e": 2.779
   },
   {
    "text": "and still be impossible in a wheelchair.",
    "s": 2.978,
    "e": 4.836
   },
   {
    "text": "Maps don't show the stairs, the steep grades, or the broken pavement.",
    "s": 5.386,
    "e": 9.311
   },
   {
    "text": "You find out when you're already there.",
    "s": 9.861,
    "e": 11.356
   }
  ],
  "words": [
   {
    "t": "A",
    "s": 0.7,
    "e": 0.875
   },
   {
    "t": "route",
    "s": 0.887,
    "e": 1.132
   },
   {
    "t": "can",
    "s": 1.144,
    "e": 1.272
   },
   {
    "t": "look",
    "s": 1.284,
    "e": 1.424
   },
   {
    "t": "completely",
    "s": 1.436,
    "e": 1.915
   },
   {
    "t": "valid",
    "s": 1.927,
    "e": 2.242
   },
   {
    "t": "on",
    "s": 2.254,
    "e": 2.382
   },
   {
    "t": "a",
    "s": 2.394,
    "e": 2.417
   },
   {
    "t": "map",
    "s": 2.429,
    "e": 2.779
   },
   {
    "t": "and",
    "s": 2.978,
    "e": 3.153
   },
   {
    "t": "still",
    "s": 3.165,
    "e": 3.434
   },
   {
    "t": "be",
    "s": 3.445,
    "e": 3.539
   },
   {
    "t": "impossible",
    "s": 3.55,
    "e": 4.123
   },
   {
    "t": "in",
    "s": 4.135,
    "e": 4.216
   },
   {
    "t": "a",
    "s": 4.228,
    "e": 4.275
   },
   {
    "t": "wheelchair",
    "s": 4.286,
    "e": 4.836
   },
   {
    "t": "Maps",
    "s": 5.386,
    "e": 5.806
   },
   {
    "t": "don't",
    "s": 5.818,
    "e": 5.993
   },
   {
    "t": "show",
    "s": 6.005,
    "e": 6.203
   },
   {
    "t": "the",
    "s": 6.215,
    "e": 6.297
   },
   {
    "t": "stairs",
    "s": 6.308,
    "e": 6.799
   },
   {
    "t": "the",
    "s": 6.951,
    "e": 7.044
   },
   {
    "t": "steep",
    "s": 7.056,
    "e": 7.395
   },
   {
    "t": "grades",
    "s": 7.407,
    "e": 7.897
   },
   {
    "t": "or",
    "s": 7.979,
    "e": 8.224
   },
   {
    "t": "the",
    "s": 8.248,
    "e": 8.353
   },
   {
    "t": "broken",
    "s": 8.364,
    "e": 8.727
   },
   {
    "t": "pavement",
    "s": 8.738,
    "e": 9.311
   },
   {
    "t": "You",
    "s": 9.861,
    "e": 10.059
   },
   {
    "t": "find",
    "s": 10.071,
    "e": 10.351
   },
   {
    "t": "out",
    "s": 10.363,
    "e": 10.48
   },
   {
    "t": "when",
    "s": 10.492,
    "e": 10.585
   },
   {
    "t": "you're",
    "s": 10.597,
    "e": 10.702
   },
   {
    "t": "already",
    "s": 10.714,
    "e": 11.052
   },
   {
    "t": "there",
    "s": 11.064,
    "e": 11.356
   }
  ]
 },
 "turn": {
  "start": 18.52,
  "duration": 8.96,
  "clips": [
   {
    "file": "audio/turn-0.mp3",
    "start": 1.1
   },
   {
    "file": "audio/turn-1.mp3",
    "start": 5.517
   },
   {
    "file": "audio/turn-2.mp3",
    "start": 6.676
   }
  ],
  "captions": [
   {
    "text": "Tandem walks the route first,",
    "s": 1.2,
    "e": 2.66
   },
   {
    "text": "and checks it for accessibility barriers.",
    "s": 2.894,
    "e": 5.067
   },
   {
    "text": "No new app.",
    "s": 5.617,
    "e": 6.376
   },
   {
    "text": "You just text where you're going.",
    "s": 6.776,
    "e": 8.061
   }
  ],
  "words": [
   {
    "t": "Tandem",
    "s": 1.2,
    "e": 1.656
   },
   {
    "t": "walks",
    "s": 1.667,
    "e": 1.924
   },
   {
    "t": "the",
    "s": 1.936,
    "e": 2.029
   },
   {
    "t": "route",
    "s": 2.041,
    "e": 2.24
   },
   {
    "t": "first",
    "s": 2.251,
    "e": 2.66
   },
   {
    "t": "and",
    "s": 2.894,
    "e": 3.046
   },
   {
    "t": "checks",
    "s": 3.081,
    "e": 3.35
   },
   {
    "t": "it",
    "s": 3.361,
    "e": 3.513
   },
   {
    "t": "for",
    "s": 3.525,
    "e": 3.642
   },
   {
    "t": "accessibility",
    "s": 3.653,
    "e": 4.413
   },
   {
    "t": "barriers",
    "s": 4.424,
    "e": 5.067
   },
   {
    "t": "No",
    "s": 5.617,
    "e": 5.886
   },
   {
    "t": "new",
    "s": 5.897,
    "e": 6.049
   },
   {
    "t": "app.",
    "s": 6.061,
    "e": 6.376
   },
   {
    "t": "You",
    "s": 6.776,
    "e": 6.975
   },
   {
    "t": "just",
    "s": 6.986,
    "e": 7.15
   },
   {
    "t": "text",
    "s": 7.162,
    "e": 7.43
   },
   {
    "t": "where",
    "s": 7.442,
    "e": 7.559
   },
   {
    "t": "you're",
    "s": 7.571,
    "e": 7.676
   },
   {
    "t": "going",
    "s": 7.687,
    "e": 8.061
   }
  ]
 },
 "request": {
  "start": 26.98,
  "duration": 7.28,
  "clips": [
   {
    "file": "audio/request-0.mp3",
    "start": 0.6
   }
  ],
  "captions": [
   {
    "text": "You tell it where you're headed and how you get around,",
    "s": 0.7,
    "e": 2.861
   },
   {
    "text": "the same way you'd text a friend.",
    "s": 3.212,
    "e": 4.882
   }
  ],
  "words": [
   {
    "t": "You",
    "s": 0.7,
    "e": 0.864
   },
   {
    "t": "tell",
    "s": 0.875,
    "e": 1.086
   },
   {
    "t": "it",
    "s": 1.097,
    "e": 1.179
   },
   {
    "t": "where",
    "s": 1.191,
    "e": 1.319
   },
   {
    "t": "you're",
    "s": 1.331,
    "e": 1.448
   },
   {
    "t": "headed",
    "s": 1.459,
    "e": 1.821
   },
   {
    "t": "and",
    "s": 1.845,
    "e": 1.985
   },
   {
    "t": "how",
    "s": 1.997,
    "e": 2.125
   },
   {
    "t": "you",
    "s": 2.137,
    "e": 2.254
   },
   {
    "t": "get",
    "s": 2.265,
    "e": 2.429
   },
   {
    "t": "around",
    "s": 2.441,
    "e": 2.861
   },
   {
    "t": "the",
    "s": 3.212,
    "e": 3.305
   },
   {
    "t": "same",
    "s": 3.317,
    "e": 3.667
   },
   {
    "t": "way",
    "s": 3.679,
    "e": 3.854
   },
   {
    "t": "you'd",
    "s": 3.866,
    "e": 4.041
   },
   {
    "t": "text",
    "s": 4.053,
    "e": 4.345
   },
   {
    "t": "a",
    "s": 4.357,
    "e": 4.403
   },
   {
    "t": "friend",
    "s": 4.415,
    "e": 4.882
   }
  ]
 },
 "scout": {
  "start": 33.76,
  "duration": 24.24,
  "clips": [
   {
    "file": "audio/scout-0.mp3",
    "start": 1.6
   },
   {
    "file": "audio/scout-1.mp3",
    "start": 8.398
   },
   {
    "file": "audio/scout-2.mp3",
    "start": 9.424
   },
   {
    "file": "audio/scout-3.mp3",
    "start": 10.45
   },
   {
    "file": "audio/scout-4.mp3",
    "start": 12.375
   },
   {
    "file": "audio/scout-5.mp3",
    "start": 14.426
   },
   {
    "file": "audio/scout-6.mp3",
    "start": 17.427
   }
  ],
  "captions": [
   {
    "text": "Tandem samples Street View along each candidate route,",
    "s": 1.7,
    "e": 4.656
   },
   {
    "text": "and checks every photo for barriers to a wheelchair.",
    "s": 5.053,
    "e": 7.798
   },
   {
    "text": "Clear.",
    "s": 8.498,
    "e": 9.024
   },
   {
    "text": "Clear.",
    "s": 9.524,
    "e": 10.05
   },
   {
    "text": "Clear.",
    "s": 10.55,
    "e": 11.075
   },
   {
    "text": "Then, fourteen steps.",
    "s": 12.475,
    "e": 14.076
   },
   {
    "text": "No ramp.",
    "s": 14.526,
    "e": 15.227
   },
   {
    "text": "It also checks signals like elevation,",
    "s": 17.527,
    "e": 19.618
   },
   {
    "text": "so it can show you the tradeoffs instead of hiding them.",
    "s": 19.992,
    "e": 22.644
   }
  ],
  "words": [
   {
    "t": "Tandem",
    "s": 1.7,
    "e": 2.144
   },
   {
    "t": "samples",
    "s": 2.156,
    "e": 2.6
   },
   {
    "t": "Street",
    "s": 2.611,
    "e": 2.88
   },
   {
    "t": "View",
    "s": 2.892,
    "e": 3.184
   },
   {
    "t": "along",
    "s": 3.207,
    "e": 3.593
   },
   {
    "t": "each",
    "s": 3.616,
    "e": 3.838
   },
   {
    "t": "candidate",
    "s": 3.85,
    "e": 4.364
   },
   {
    "t": "route",
    "s": 4.375,
    "e": 4.656
   },
   {
    "t": "and",
    "s": 5.053,
    "e": 5.205
   },
   {
    "t": "checks",
    "s": 5.275,
    "e": 5.567
   },
   {
    "t": "every",
    "s": 5.672,
    "e": 5.882
   },
   {
    "t": "photo",
    "s": 5.894,
    "e": 6.291
   },
   {
    "t": "for",
    "s": 6.303,
    "e": 6.455
   },
   {
    "t": "barriers",
    "s": 6.466,
    "e": 7.015
   },
   {
    "t": "to",
    "s": 7.027,
    "e": 7.144
   },
   {
    "t": "a",
    "s": 7.156,
    "e": 7.214
   },
   {
    "t": "wheelchair",
    "s": 7.226,
    "e": 7.798
   },
   {
    "t": "Clear",
    "s": 8.498,
    "e": 9.024
   },
   {
    "t": "Clear",
    "s": 9.524,
    "e": 10.05
   },
   {
    "t": "Clear",
    "s": 10.55,
    "e": 11.075
   },
   {
    "t": "Then",
    "s": 12.475,
    "e": 12.872
   },
   {
    "t": "fourteen",
    "s": 13.118,
    "e": 13.573
   },
   {
    "t": "steps",
    "s": 13.585,
    "e": 14.076
   },
   {
    "t": "No",
    "s": 14.526,
    "e": 14.818
   },
   {
    "t": "ramp",
    "s": 14.829,
    "e": 15.227
   },
   {
    "t": "It",
    "s": 17.527,
    "e": 17.702
   },
   {
    "t": "also",
    "s": 17.714,
    "e": 17.971
   },
   {
    "t": "checks",
    "s": 17.982,
    "e": 18.263
   },
   {
    "t": "signals",
    "s": 18.274,
    "e": 18.66
   },
   {
    "t": "like",
    "s": 18.672,
    "e": 18.894
   },
   {
    "t": "elevation",
    "s": 19.01,
    "e": 19.618
   },
   {
    "t": "so",
    "s": 19.992,
    "e": 20.249
   },
   {
    "t": "it",
    "s": 20.272,
    "e": 20.365
   },
   {
    "t": "can",
    "s": 20.377,
    "e": 20.529
   },
   {
    "t": "show",
    "s": 20.541,
    "e": 20.751
   },
   {
    "t": "you",
    "s": 20.763,
    "e": 20.868
   },
   {
    "t": "the",
    "s": 20.879,
    "e": 20.961
   },
   {
    "t": "tradeoffs",
    "s": 20.973,
    "e": 21.534
   },
   {
    "t": "instead",
    "s": 21.545,
    "e": 21.966
   },
   {
    "t": "of",
    "s": 21.978,
    "e": 22.048
   },
   {
    "t": "hiding",
    "s": 22.059,
    "e": 22.328
   },
   {
    "t": "them",
    "s": 22.34,
    "e": 22.644
   }
  ]
 },
 "proof": {
  "start": 57.5,
  "duration": 8.92,
  "clips": [
   {
    "file": "audio/proof-0.mp3",
    "start": 0.8
   },
   {
    "file": "audio/proof-1.mp3",
    "start": 2.593
   }
  ],
  "captions": [
   {
    "text": "And it shows its evidence.",
    "s": 0.9,
    "e": 2.243
   },
   {
    "text": "You get the photo it flagged, when that image was taken,",
    "s": 2.693,
    "e": 5.778
   },
   {
    "text": "and a preview of the route before you leave.",
    "s": 6.046,
    "e": 8.021
   }
  ],
  "words": [
   {
    "t": "And",
    "s": 0.9,
    "e": 1.169
   },
   {
    "t": "it",
    "s": 1.18,
    "e": 1.262
   },
   {
    "t": "shows",
    "s": 1.274,
    "e": 1.578
   },
   {
    "t": "its",
    "s": 1.589,
    "e": 1.718
   },
   {
    "t": "evidence",
    "s": 1.729,
    "e": 2.243
   },
   {
    "t": "You",
    "s": 2.693,
    "e": 2.88
   },
   {
    "t": "get",
    "s": 2.892,
    "e": 3.056
   },
   {
    "t": "the",
    "s": 3.067,
    "e": 3.149
   },
   {
    "t": "photo",
    "s": 3.161,
    "e": 3.5
   },
   {
    "t": "it",
    "s": 3.511,
    "e": 3.605
   },
   {
    "t": "flagged",
    "s": 3.616,
    "e": 4.154
   },
   {
    "t": "when",
    "s": 4.446,
    "e": 4.586
   },
   {
    "t": "that",
    "s": 4.598,
    "e": 4.761
   },
   {
    "t": "image",
    "s": 4.843,
    "e": 5.123
   },
   {
    "t": "was",
    "s": 5.135,
    "e": 5.275
   },
   {
    "t": "taken",
    "s": 5.287,
    "e": 5.778
   },
   {
    "t": "and",
    "s": 6.046,
    "e": 6.233
   },
   {
    "t": "a",
    "s": 6.245,
    "e": 6.303
   },
   {
    "t": "preview",
    "s": 6.315,
    "e": 6.771
   },
   {
    "t": "of",
    "s": 6.782,
    "e": 6.852
   },
   {
    "t": "the",
    "s": 6.864,
    "e": 6.946
   },
   {
    "t": "route",
    "s": 6.957,
    "e": 7.156
   },
   {
    "t": "before",
    "s": 7.168,
    "e": 7.46
   },
   {
    "t": "you",
    "s": 7.471,
    "e": 7.565
   },
   {
    "t": "leave",
    "s": 7.577,
    "e": 8.021
   }
  ]
 },
 "better": {
  "start": 65.92,
  "duration": 13.84,
  "clips": [
   {
    "file": "audio/better-0.mp3",
    "start": 0.6
   },
   {
    "file": "audio/better-1.mp3",
    "start": 5.943
   },
   {
    "file": "audio/better-2.mp3",
    "start": 8.666
   }
  ],
  "captions": [
   {
    "text": "Here, the direct route takes 9.4 minutes,",
    "s": 0.7,
    "e": 3.574
   },
   {
    "text": "and runs straight into the stairs.",
    "s": 3.749,
    "e": 5.443
   },
   {
    "text": "The alternative takes 9.5.",
    "s": 6.043,
    "e": 8.216
   },
   {
    "text": "It avoids the staircase,",
    "s": 8.766,
    "e": 10.098
   },
   {
    "text": "while still warning you about the steep climb ahead.",
    "s": 10.214,
    "e": 12.644
   }
  ],
  "words": [
   {
    "t": "Here",
    "s": 0.7,
    "e": 1.109
   },
   {
    "t": "the",
    "s": 1.389,
    "e": 1.471
   },
   {
    "t": "direct",
    "s": 1.483,
    "e": 1.81
   },
   {
    "t": "route",
    "s": 1.821,
    "e": 2.008
   },
   {
    "t": "takes",
    "s": 2.02,
    "e": 2.312
   },
   {
    "t": "nine",
    "s": 2.324,
    "e": 2.686
   },
   {
    "t": "point",
    "s": 2.698,
    "e": 2.966
   },
   {
    "t": "four",
    "s": 2.978,
    "e": 3.165
   },
   {
    "t": "minutes",
    "s": 3.177,
    "e": 3.574
   },
   {
    "t": "and",
    "s": 3.749,
    "e": 3.936
   },
   {
    "t": "runs",
    "s": 3.948,
    "e": 4.251
   },
   {
    "t": "straight",
    "s": 4.263,
    "e": 4.637
   },
   {
    "t": "into",
    "s": 4.649,
    "e": 4.8
   },
   {
    "t": "the",
    "s": 4.812,
    "e": 4.894
   },
   {
    "t": "stairs",
    "s": 4.906,
    "e": 5.443
   },
   {
    "t": "The",
    "s": 6.043,
    "e": 6.195
   },
   {
    "t": "alternative",
    "s": 6.207,
    "e": 6.814
   },
   {
    "t": "takes",
    "s": 6.826,
    "e": 7.129
   },
   {
    "t": "nine",
    "s": 7.141,
    "e": 7.492
   },
   {
    "t": "point",
    "s": 7.503,
    "e": 7.737
   },
   {
    "t": "five",
    "s": 7.749,
    "e": 8.216
   },
   {
    "t": "It",
    "s": 8.766,
    "e": 8.929
   },
   {
    "t": "avoids",
    "s": 8.941,
    "e": 9.315
   },
   {
    "t": "the",
    "s": 9.327,
    "e": 9.42
   },
   {
    "t": "staircase",
    "s": 9.432,
    "e": 10.098
   },
   {
    "t": "while",
    "s": 10.214,
    "e": 10.448
   },
   {
    "t": "still",
    "s": 10.46,
    "e": 10.81
   },
   {
    "t": "warning",
    "s": 10.822,
    "e": 11.126
   },
   {
    "t": "you",
    "s": 11.137,
    "e": 11.278
   },
   {
    "t": "about",
    "s": 11.289,
    "e": 11.511
   },
   {
    "t": "the",
    "s": 11.523,
    "e": 11.616
   },
   {
    "t": "steep",
    "s": 11.628,
    "e": 11.979
   },
   {
    "t": "climb",
    "s": 11.99,
    "e": 12.282
   },
   {
    "t": "ahead",
    "s": 12.294,
    "e": 12.644
   }
  ]
 },
 "closing": {
  "start": 79.26,
  "duration": 11.45,
  "clips": [
   {
    "file": "audio/closing-0.mp3",
    "start": 0.7
   },
   {
    "file": "audio/closing-1.mp3",
    "start": 3.645
   },
   {
    "file": "audio/closing-2.mp3",
    "start": 7.051
   },
   {
    "file": "audio/closing-3.mp3",
    "start": 8.012
   }
  ],
  "captions": [
   {
    "text": "Navigation shouldn't just know where a path goes.",
    "s": 0.8,
    "e": 3.195
   },
   {
    "text": "It should tell you whether that path is accessible to you.",
    "s": 3.745,
    "e": 6.151
   },
   {
    "text": "Tandem.",
    "s": 7.151,
    "e": 7.712
   },
   {
    "text": "It walks the route before you do.",
    "s": 8.112,
    "e": 9.654
   }
  ],
  "words": [
   {
    "t": "Navigation",
    "s": 0.8,
    "e": 1.524
   },
   {
    "t": "shouldn't",
    "s": 1.536,
    "e": 1.84
   },
   {
    "t": "just",
    "s": 1.851,
    "e": 2.062
   },
   {
    "t": "know",
    "s": 2.073,
    "e": 2.26
   },
   {
    "t": "where",
    "s": 2.272,
    "e": 2.4
   },
   {
    "t": "a",
    "s": 2.412,
    "e": 2.459
   },
   {
    "t": "path",
    "s": 2.471,
    "e": 2.763
   },
   {
    "t": "goes",
    "s": 2.774,
    "e": 3.195
   },
   {
    "t": "It",
    "s": 3.745,
    "e": 3.92
   },
   {
    "t": "should",
    "s": 3.932,
    "e": 4.095
   },
   {
    "t": "tell",
    "s": 4.107,
    "e": 4.282
   },
   {
    "t": "you",
    "s": 4.294,
    "e": 4.387
   },
   {
    "t": "whether",
    "s": 4.399,
    "e": 4.621
   },
   {
    "t": "that",
    "s": 4.633,
    "e": 4.773
   },
   {
    "t": "path",
    "s": 4.785,
    "e": 5.147
   },
   {
    "t": "is",
    "s": 5.158,
    "e": 5.24
   },
   {
    "t": "accessible",
    "s": 5.252,
    "e": 5.789
   },
   {
    "t": "to",
    "s": 5.801,
    "e": 5.894
   },
   {
    "t": "you",
    "s": 5.906,
    "e": 6.151
   },
   {
    "t": "Tandem",
    "s": 7.151,
    "e": 7.712
   },
   {
    "t": "It",
    "s": 8.112,
    "e": 8.276
   },
   {
    "t": "walks",
    "s": 8.287,
    "e": 8.556
   },
   {
    "t": "the",
    "s": 8.568,
    "e": 8.661
   },
   {
    "t": "route",
    "s": 8.673,
    "e": 8.848
   },
   {
    "t": "before",
    "s": 8.86,
    "e": 9.152
   },
   {
    "t": "you",
    "s": 9.164,
    "e": 9.257
   },
   {
    "t": "do",
    "s": 9.269,
    "e": 9.654
   }
  ]
 }
};
